### ISSUE TITLE
when i add new kubeconfig, something was wrong

### ISSUE THREAD

**Issue by logerror** [lensapp/lens#3240] opened 2021-07-01 08:11 UTC
![image](https://user-images.githubusercontent.com/13896386/124089838-dccfa280-da86-11eb-8c6e-c3d0660b66ce.png)

**Comment by logerror** [comment] 2021-07-01 10:19
windows 10

**Comment by jim-docker** [comment] 2021-07-05 15:58
Hi, can you share the kubeconfig, omitting sensitive data? Does `kubectl` work with this kubeconfig?

**Comment by logerror** [comment] 2021-07-09 03:17
kubectl is work

**Comment by logerror** [comment] 2021-07-09 03:19
![image](https://user-images.githubusercontent.com/13896386/125018372-8aeed400-e0a7-11eb-9458-ef0511f59be4.png)

**Comment by jim-docker** [comment] 2021-07-21 20:37
Thanks, I made a config file that looks like that (same content, names) but could not reproduce the error on Windows 10. How did you add the kubeconfig file to Lens? Did you get that error right after adding it?

**Comment by Nokel81** [comment] 2021-07-22 14:41
@logerror Is this still an issue with Lens5? It might have been resolved since 4.2.5.

**Comment by logerror** [comment] 2021-07-28 14:26
I did not reproduce it

**Comment by Nokel81** [comment] 2021-07-28 17:24
Okay thanks. I will close this then as I believe that we fixed that issue.

**Closed as completed by Nokel81** 2021-07-28 17:24 UTC
Labels: bug
