### ISSUE TITLE
make closing multiple tabs easier

### ISSUE THREAD

**Issue by matti** [lensapp/lens#1777] opened 2020-12-15 06:42 UTC
![image](https://user-images.githubusercontent.com/3893/102180375-6e900d80-3eb1-11eb-88b1-ecbb88b1dc1d.png)

it's really hard to close multiple tabs because the tabs don't have equal width (not that they should, tho)

**Comment by nevalla** [comment] 2020-12-21 14:12
Duplicate of #290. Let's monitor the resolution on that issue.

**Closed as completed by nevalla** 2020-12-21 14:12 UTC
Labels: enhancement
