### ISSUE TITLE
Enable user-selected Prometheus-labels (instead of 'kubernetes_node')

### ISSUE THREAD

**Issue by ninlil** [lensapp/lens#2177] opened 2021-02-18 08:15 UTC
**What would you like to be added**:

Allow the prometheus-labels to be chosen, not require it to be called 'kubernetes_node'

**Why is this needed**:

We are already running a couple of clusters using Thanos, Prometheus-operators, Grafana, Alertmanager and Karma.. and have already relabeled the node hostname into just 'node'.

We do not want to:
a) rename 'node' into 'kubernetes_node' and have to rewrite a lot of queries in alerts, rules, graph-queries a.s.o.
b) duplicate the 'node' label thus increasing the number of labels in our data

Please add an option for us to type in what the required labels are, instead of forcing us to change already established architecture.

**Environment you are Lens application on:**

- Kubernetes distribution: AKS
- Desktop OS: Windows 10, macOS

**Comment by Nokel81** [comment] 2022-11-18 19:59
Duplicate of #3955

**Closed as completed by Nokel81** 2022-11-18 19:59 UTC
Labels: enhancement
