### ISSUE TITLE
Cluster submenu items referencing same page are both highlighted

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#1457] opened 2020-11-19 23:46 UTC
```
  clusterPageMenus = [
    {
      id: "example",
      title: "Greetings",
      components: {
        Icon: ExampleIcon,
      }
    },
    {
      parentId: "example",
      target: { pageId: "hello" },
      title: "Hello World",
      components: {
        Icon: ExampleIcon,
      }
    },
    {
      parentId: "example",
      target: { pageId: "hello" },
      title: "Bonjour le monde",
      components: {
        Icon: ExempleIcon,
      }
    }
  ]
```
![image](https://user-images.githubusercontent.com/40840436/99737131-ac0da080-2a95-11eb-89bd-e40dc1e6a51d.png)

It's an odd thing to do so maybe this is ok? Although, theoretically one could specify the same page with different params to pass it thus yielding a different route.

**Comment by jakolehm** [comment] 2020-11-20 06:39
Currently this is "by design". Sidebar does "isActive" matching based on routes so if multiple menu items points to a same route then they will be highlighted. ~Should not be an issue until extension api allows to do cross-referencing.~

**Comment by Nokel81** [comment] 2021-03-25 15:59
If this is by design shall we close this issue then?

**Comment by jim-docker** [comment] 2021-03-25 16:10
> If this is by design shall we close this issue then?

Just tested on 4.1.4, and it is appears to be fixed anyway (must be now including params in the route determination?)

**Comment by Nokel81** [comment] 2021-03-25 16:12
Cool, thanks for the update.

**Closed as completed by Nokel81** 2021-03-25 16:12 UTC
Labels: area/ui, area/extension

**Comment by jim-docker** [comment] 2021-03-25 16:22
Actually, it may not be fixed (my test extension does it slightly differently) but there is an easy workaround, which is a more correct way to do it anyway.
