### ISSUE TITLE
Lens reports missing kubeconfig as invalid

### ISSUE THREAD

**Issue by ccremer** [lensapp/lens#2343] opened 2021-03-16 16:44 UTC
**Describe the bug**

I get an annoying red notification that a missing kubeconfig is invalid.
The link to the kubeconfig within that notification is just not doing anything.

**To Reproduce**
1. Make a KIND cluster, e.g. `KUBECONFIG=my-config kind create cluster --name lens-test` (not tested, but extracted from a Makefile)
2. Add the cluster to lens
3. Quit Lens
4. Delete kubeconfig `my-config`
5. Start lens

**Expected behavior**
Either:
1) Save a "ignore this error for this cluster" action so it doesn't bother me again. Useful for kubeconfigs that may actually be working. But don't know if that can happen.
2) Only pop notifications for the current workspace, but ignore invalid or missing kubeconfigs in other workspaces as long as I don't switch the workspace.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 4.1.4
- OS: KDE neon
- Installation method (e.g. snap or AppImage in Linux): snap

**Logs:**
```
info: 🚀 Starting Lens from "/home/chris/snap/kontena-lens/165/.config/Lens"
info: 🐚 Syncing shell environment
info: 💾 Loading stores
info: [STORE]: LOADED from /home/chris/snap/kontena-lens/165/.config/Lens/config.json
info: [STORE]: LOADED from /home/chris/snap/kontena-lens/165/.config/Lens/lens-cluster-store.json
error: No valid context object provided in kubeconfig for context 'kind-k8up-v1.20.0'
error: [CLUSTER] Failed to load kubeconfig for the cluster 'kind-k8up-v1.20.0' (context: kind-k8up-v1.20.0, kubeconfig: <redacted>/bin/kind-kubeconfig-v1.20.0).
info: [STORE]: LOADED from /home/chris/snap/kontena-lens/165/.config/Lens/lens-workspace-store.json
...
```

**Kubeconfig:**
well, it's not there :)

**Additional context**
We use often KIND clusters as a throwaway cluster for local development, usually with `make`.
e.g. `make e2e-test` spins up a KIND cluster, creates the kubeconfig, does the tests.
upon `make clean` the cluster is being deleted, including kubeconfig to get a completely clean slate.

Now, between running the tests and cleaning up, I use Lens to do some manual inspections from time to time, e.g. logs etc.

The annoying part is that the notification pops up even though I'm using a different workspace for a different project (but also with KIND). So I would be fine if the notifications only pop up when I switch to that workspace where the kubeconfig is relevant.

**Comment by jim-docker** [comment] 2021-03-22 15:05
Thanks for the report and suggestions. We are seeing similar problems with how we're handling this (#2326). We will investigate ways to make the UX smoother.

**Comment by Nokel81** [comment] 2021-03-25 19:33
Duplicate of #843

**Closed as completed by Nokel81** 2021-03-25 19:33 UTC
Labels: bug
