### ISSUE TITLE
PID xxxxx/kontena-lens listening on port 45657

### ISSUE THREAD

**Issue by rgherta** [lensapp/lens#2633] opened 2021-04-26 22:28 UTC
I installed Lens via ubuntu software / snap.
I opened the program then closed it.

The process is still running and listening on port 45657

**Comment by Nokel81** [comment] 2021-04-27 13:07
That is because there is a tray icon and the process it still running. Duplicate of #2213

**Closed as completed by Nokel81** 2021-04-27 13:07 UTC
