### ISSUE TITLE
Lens can not find AWS command and not connecting on MacOS

### ISSUE THREAD

**Issue by amittropper** [lensapp/lens#1557] opened 2020-11-28 11:04 UTC
I am unable to connect Lens to my K8S cluster, seem that once Lens starts it need the AWS CLI command and it can not find it although it is set in the env $PATH. I assume that once Lens start it parse the env variables and for some reason it can not parse the env variables. I pasted the output of running Lens from the terminal below:

Steps:
1. Open terminal window on my MacOS 
2. Connect to my remote K8S cluster using Okta
3. Set the K8S cluster env
4. Verify that I can do kubctl get pod 
5. Start Lens from the same shell

The following is the terminal output of running Lens command:

./Lens
info: [IPC]: setup channel "cluster:activate"
info: [IPC]: setup channel "cluster:set-frame-id"
info: [IPC]: setup channel "cluster:refresh"
info: [IPC]: setup channel "cluster:disconnect"
info: [IPC]: setup channel "cluster:install-feature"
info: [IPC]: setup channel "cluster:uninstall-feature"
info: [IPC]: setup channel "cluster:upgrade-feature"
error: shellEnv: Error: Command failed: /bin/tcsh -ilc echo -n "_SHELL_ENV_DELIMITER_"; env; echo -n "_SHELL_ENV_DELIMITER_"; exit
Unknown option: `-lc'
Usage: tcsh [ -bcdefilmnqstvVxX ] [ argument ... ].

info: 🚀 Starting Lens from "/Users/atropper/Library/Application Support/Lens"
info: Checking for update
info: [STORE]: LOADED from /Users/atropper/Library/Application Support/Lens/config.json
info: [STORE]: LOADED from /Users/atropper/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /Users/atropper/Library/Application Support/Lens/lens-workspace-store.json
info: [CLUSTER-MANAGER]: init cluster {"id":"f359c09d-e1b8-4241-9792-c1c3f33ef62b","name":"arn:aws:eks:us-east-1:733937772608:cluster/eyesightx-env-dev2-cluster","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: "arn:aws:eks:us-east-1:733937772608:cluster/eyesightx-env-dev2-cluster" init success {"id":"f359c09d-e1b8-4241-9792-c1c3f33ef62b","context":"arn:aws:eks:us-east-1:733937772608:cluster/eyesightx-env-dev2-cluster","apiUrl":"https://5ECFA7EDDB0FCCFD267719E7962AD91A.gr7.us-east-1.eks.amazonaws.com"}
info: LensProxy server has started at http://localhost:54226
/bin/sh: ioreg: command not found
info: [CLUSTER]: activate {"id":"f359c09d-e1b8-4241-9792-c1c3f33ef62b","name":"arn:aws:eks:us-east-1:733937772608:cluster/eyesightx-env-dev2-cluster","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: bind events {"id":"f359c09d-e1b8-4241-9792-c1c3f33ef62b","name":"arn:aws:eks:us-east-1:733937772608:cluster/eyesightx-env-dev2-cluster","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: reconnect {"id":"f359c09d-e1b8-4241-9792-c1c3f33ef62b","name":"arn:aws:eks:us-east-1:733937772608:cluster/eyesightx-env-dev2-cluster","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: Update for version 3.6.9 is not available (latest version: 3.6.9, downgrade is disallowed).
info: [KUBE-AUTH]: out-channel "kube-auth:f359c09d-e1b8-4241-9792-c1c3f33ef62b" {"data":"Authentication proxy started\n","meta":{"id":"f359c09d-e1b8-4241-9792-c1c3f33ef62b","name":"arn:aws:eks:us-east-1:733937772608:cluster/eyesightx-env-dev2-cluster","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}}
/bin/sh: ioreg: command not found
info: [KUBE-AUTH]: out-channel "kube-auth:f359c09d-e1b8-4241-9792-c1c3f33ef62b" {"data":"2020/11/28 12:49:14 http: proxy error: getting credentials: exec: exec: \"aws\": executable file not found in $PATH\n","error":true,"meta":{"id":"f359c09d-e1b8-4241-9792-c1c3f33ef62b","name":"arn:aws:eks:us-east-1:733937772608:cluster/eyesightx-env-dev2-cluster","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}}
info: [KUBE-AUTH]: out-channel "kube-auth:f359c09d-e1b8-4241-9792-c1c3f33ef62b" {"data":"2020/11/28 12:49:14 http: proxy error: getting credentials: exec: exec: \"aws\": executable file not found in $PATH\n","error":true,"meta":{"id":"f359c09d-e1b8-4241-9792-c1c3f33ef62b","name":"arn:aws:eks:us-east-1:733937772608:cluster/eyesightx-env-dev2-cluster","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":false}}
error: Failed to connect cluster "arn:aws:eks:us-east-1:733937772608:cluster/eyesightx-env-dev2-cluster": StatusCodeError: 502 - undefined
info: Closing proxy server
info: [CLUSTER]: disconnect {"id":"f359c09d-e1b8-4241-9792-c1c3f33ef62b","name":"arn:aws:eks:us-east-1:733937772608:cluster/eyesightx-env-dev2-cluster","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":false}
info: [CLUSTER]: unbind events {"id":"f359c09d-e1b8-4241-9792-c1c3f33ef62b","name":"arn:aws:eks:us-east-1:733937772608:cluster/eyesightx-env-dev2-cluster","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":false}

**Comment by nevalla** [comment] 2020-11-30 13:49
Please could you test with absolute path to `aws` binary in kubeconfig. Is it working then?

**Comment by Nokel81** [comment] 2021-03-25 16:24
duplicate of #2079 

Could be a problem with how you modify the `PATH` env var is set. If you are running Lens not from the command line then your `.bash_profile` and `.bashrc` files are not run.

**Closed as completed by Nokel81** 2021-03-25 16:24 UTC
