### ISSUE TITLE
Ability to adjust column widths

### ISSUE THREAD

**Issue by Nuru** [lensapp/lens#350] opened 2020-05-06 23:57 UTC
**What would you like to be added**:
I would like to be able to individually adjust column widths. 

(I would like lots of features regarding columns, such as the ability to hide and show columns, rearrange their order, and create a custom column, but I want to limit this issue to the single feature of being able to adjust column widths.)

**Why is this needed**:

For example, in the Pods view on my screen, some of the pod names are truncated because the column is too narrow for them to fit, while there is lots of white space around Age and Status. I would prefer to be able to modify the column widths so I can see the full name of the pod and reduce the amount of space given to Age and Status. 

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...] `kops` AWS
- Desktop OS: <the OS Lens app runs on in your case> macOS Catalina

**Comment by andrewnazarov** [comment] 2021-05-24 17:55
We would like to have it as well. We have quite long object names and usually we see only the beginning of these names that are the same for many workloads. Therefore we have to rely on tooltips which is not that practical.

**Comment by FuyuanChu** [comment] 2021-09-23 01:17
Will be much appreciated to have this feature.

**Comment by Nokel81** [comment] 2021-11-25 19:14
Closing as a duplicate of https://github.com/lensapp/lens/issues/601 as it has more 👍 's please go add yours to that issue!

**Closed as completed by Nokel81** 2021-11-25 19:14 UTC
Labels: enhancement
