### ISSUE TITLE
Draining a node opens a terminal but no command is sent

### ISSUE THREAD

**Issue by toasti** [lensapp/lens#3279] opened 2021-07-06 08:54 UTC
**Describe the bug**
In the Nodes tab of a cluster, when I click the breadcrumbs/3dots next to a node and select "Drain" a new terminal opens, but no command gets sent to that terminal from lens, which means that effectively nothing happens.

**To Reproduce**
1. Go to Nodes tab in a cluster
2. (Optional, works as expected) On a node select the breadcrumbs/3 dots to the far right, and click cordon
3. On a node select the breadcrumbs/3 dots to the far right, and click drain
4. New but empty terminal opens in lens, without a command being sent to that terminal by lens

**Expected behavior**
New terminal opens and a command gets sent, eg `kubectl drain <node>` similar to how Cordon sends `kubectl cordon <node>`.

**Environment (please complete the following information):**
- Lens Version: doesnt work in 5.0.0-latest.20210629.3, 5.0.2-latest.20210705.2
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): downloaded .dmg from website

**Comment by brtduvally** [comment] 2021-07-07 14:16
I can confirm this is also an issue in Linux .deb for 5.0.2-latest.20210705.2. 

Was also an issue in 5.0.0-latest.20210629.3

**Comment by Nokel81** [comment] 2021-07-07 14:18
I have most of a fix for this. Though given that there is an inherent race condition which is not very detectable due to how rc files are handled it will never be a perfect solution. We can definitely get the 95% of cases or better

**Comment by Nokel81** [comment] 2021-07-09 21:31
I have most of a fix for this. Though given that there is an inherent race condition which is not very detectable due to how rc files are handled it will never be a perfect solution. We can definitely get the 95% of cases or better

**Closed as completed** 2021-07-20 19:25 UTC
Labels: bug
