### ISSUE TITLE
Error: Can't find working API for the Kubernetes resource ingresses

### ISSUE THREAD

**Issue by chenhunghan** [lensapp/lens#1570] opened 2020-11-30 09:26 UTC
**Describe the bug**

There is an error message "Error: Can't find working API for the Kubernetes resource ingresses
" when opening the developer console. The error is from https://github.com/lensapp/lens/blob/master/src/renderer/api/kube-api.ts#L168

Not sure it's a real bug or just my minikube doesn't support ingress API.

**To Reproduce**
1. Open Lens
2. Toggle Developer Tools
3. See error

**Expected behavior**

no uncaught error

**Environment (please complete the following information):**
- Lens Version: 4.0.0-rc.1
- OS: Big Sur
- Installation method (e.g. snap or AppImage in Linux): .dmg
 
**Logs:**

```
Uncaught (in promise) Error: Can't find working API for the Kubernetes resource ingresses
    at r.<anonymous> (Lens.js:2)
    at c (Lens.js:2)
    at Generator._invoke (Lens.js:2)
    at Generator.forEach.e.<computed> [as next] (Lens.js:2)
    at o (Lens.js:2)
```

**Additional context**

Maybe it's because my minikube doesn't support k8s `ingress` api?

`kubectl api-versions ` returns (no ingress api)
```
admissionregistration.k8s.io/v1
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
batch/v1
batch/v1beta1
certificates.k8s.io/v1
certificates.k8s.io/v1beta1
coordination.k8s.io/v1
coordination.k8s.io/v1beta1
discovery.k8s.io/v1beta1
events.k8s.io/v1
events.k8s.io/v1beta1
extensions/v1beta1
networking.k8s.io/v1
networking.k8s.io/v1beta1
node.k8s.io/v1beta1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
scheduling.k8s.io/v1
scheduling.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
```

`kubectl version` returns
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-14T14:49:35Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by panuhorsmalahti** [comment] 2020-11-30 10:36
The ingresses should be returned from "networking.k8s.io/v1" API now. I also use minikube on Mac but can't reproduce. I think this should be fixed for 4.0.0. This could be debugged by inspecting if .e.g the different APIs are tried out in kube-api, and if so, what are the return values.

**Comment by jakolehm** [comment] 2020-11-30 11:02
I'm seeing the same behaviour.

**Comment by jakolehm** [comment] 2020-11-30 11:05
It seems to work if I enable ingress addon:

```
$ minikube addons enable ingress
🌟  The 'ingress' addon is enabled
```

**Comment by panuhorsmalahti** [comment] 2020-11-30 11:13
If there is no API to return ingresses, should we just hide the error and display an empty list of ingresses? Does any other cluster need the user to install e.g. addon for this API to exist?

**Comment by jakolehm** [comment] 2020-11-30 11:31
I think that an error would be fine if it would be caught and logged. `Uncaught (in promise) Error` looks like a bug.

**Closed as completed** 2020-12-01 09:22 UTC
Labels: discussion
