### ISSUE TITLE
The app won't launch anymore

### ISSUE THREAD

**Issue by Sryther** [lensapp/lens#971] opened 2020-09-25 08:40 UTC
**Describe the bug**
The app is launching but can't display any cluster: loading forever.

**To Reproduce**
1. Launch Kontena Lens (whether by CLI or UI)

**Expected behavior**
Accessing my Kubernetes clusters.

**Environment (please complete the following information):**
- Lens Version: 3.6.4
- OS: Ubuntu 20.04
- Installation method (e.g. snap or AppImage in Linux): snap
 
**Logs:**

```
info: [IPC]: setup channel "cluster:activate"
info: [IPC]: setup channel "cluster:refresh"
info: [IPC]: setup channel "cluster:disconnect"
info: [IPC]: setup channel "cluster:install-feature"
info: [IPC]: setup channel "cluster:uninstall-feature"
info: [IPC]: setup channel "cluster:upgrade-feature"
info: 🚀 Starting Lens from "/home/prey/snap/kontena-lens/120/.config/Lens"
info: SNAP env is defined, updater is disabled
info: [STORE]: LOADED from /home/prey/snap/kontena-lens/120/.config/Lens/config.json
info: [STORE]: LOADED from /home/prey/snap/kontena-lens/120/.config/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /home/prey/snap/kontena-lens/120/.config/Lens/lens-workspace-store.json
info: [CLUSTER-MANAGER]: init cluster {"id":"b058a8ee-479b-4ef3-bc4c-cbbe6451b403","name":"kubernetes-admin@cluster.local","initialized":false}
error: [CLUSTER]: init failed: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined {"id":"b058a8ee-479b-4ef3-bc4c-cbbe6451b403","error":{"code":"ERR_INVALID_ARG_TYPE"}}
info: [CLUSTER-MANAGER]: init cluster {"id":"5c3bb54a-faf1-4ca6-aadc-55e46174e6d6","name":"kubernetes-admin@cluster.local","initialized":false}
error: [CLUSTER]: init failed: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined {"id":"5c3bb54a-faf1-4ca6-aadc-55e46174e6d6","error":{"code":"ERR_INVALID_ARG_TYPE"}}
info: LensProxy server has started at http://localhost:42621
(node:843195) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ensureServer' of undefined
    at be.handleRequest (/snap/kontena-lens/120/resources/app.asar/static/build/main.js:1:99537)
    at Server.<anonymous> (/snap/kontena-lens/120/resources/app.asar/static/build/main.js:1:97870)
    at Server.emit (events.js:223:5)
    at Server.emit (/snap/kontena-lens/120/resources/app.asar/node_modules/spdy/lib/spdy/server.js:245:40)
    at parserOnIncoming (_http_server.js:748:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at socketOnData (_http_server.js:527:22)
    at Socket.emit (events.js:223:5)
    at Socket.Readable.read (_stream_readable.js:526:10)
    at Socket.read (net.js:614:39)
(node:843195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:843195) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nevalla** [comment] 2020-09-25 09:56
I think this is the same issue as reported here: https://github.com/lensapp/lens/issues/951

**Comment by Sryther** [comment] 2020-09-25 10:26
You're right.
I followed the instructions and modified the `$HOME/snap/kontena-lens/current/.config/Lens/lens-cluster-store.json` file and changed the path of kubeconfigs from `"kubeConfigPath": "/home/<user>/snap/kontena-lens/116/..."` to `"kubeConfigPath": "/home/<user>/snap/kontena-lens/current/..."`.

Now the app is starting well. Thanks!

I don't know if the issue will appear again for the next update.

**Comment by nevalla** [comment] 2020-09-25 11:32
Duplicate of #951. Let's track the progress there.

**Closed as completed by nevalla** 2020-09-25 11:32 UTC
Labels: bug, duplicate
