### ISSUE TITLE
Align ClusterRoles details pane Rules section with that of Roles.

### ISSUE THREAD

**Issue by matglas** [lensapp/lens#3483] opened 2021-07-22 11:12 UTC
**What would you like to be changed**:
When you view a ClusterRole from the ClusterRoles page it opens the Details pane on the right.
In that pane you have the Rules section. The Rules section in the same pane for a Role show a nice table like display for each resource. But the ClusterRole pane is displaying plain text.

**Why is this needed**:
The ClusterRole details pane should be aligned with that of the Role pane then its probably fixed.

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: MacOs

**Comment by Nokel81** [comment] 2021-07-22 13:38
Duplicate of #3429 will be fixed in 5.1.3

**Closed as completed by Nokel81** 2021-07-22 13:38 UTC
Labels: enhancement

**Comment by matglas** [comment] 2021-07-22 14:57
Great! I looked but has bot seen it thanks.
