### ISSUE TITLE
Cannot create a KubeObject from undefined

### ISSUE THREAD

**Issue by gerhardcit** [lensapp/lens#4543] opened 2021-12-09 14:25 UTC
**Describe the bug**
Error stack:

TypeError: Cannot create a KubeObject from undefined
    at new KubeObject (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:32750:19)
    at new WorkloadKubeObject (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:124953:1)
    at new Pod (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:154508:9)
    at http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/chunks/5.js:7217:17
    at http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:10557:49
    at http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:10521:25
    at trackDerivedFunction (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:3120:18)
    at Reaction.track (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:3649:18)
    at useObserver (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:10519:14)
    at wrappedComponent (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:10557:16)
    at Ch (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:556346:137)
    at li (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:556369:154)
    at ki (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:556367:169)
    at ii (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:556366:178)
    at ck (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:556463:126)
    at bk (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:556439:347)

Component stack:

    at wrappedComponent (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:10557:16)
    at div
    at Logs (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/chunks/5.js:7285:9)
    at div
    at div
    at Dock (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/chunks/5.js:7717:9)
    at div
    at div
    at MainLayout (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:286596:9)
    at ErrorBoundary (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:237949:9)
    at Router (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:79054:30)
    at ClusterFrame (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/chunks/5.js:7946:9)
    at ThemeProvider (http://ba01f7644afcf8d4033bd4d02af93ddb.localhost:64609/build/Lens.js:609860:24)

**To Reproduce**
Suddenly just started happening while connecting to a cluster that's been running all day.

**Expected behavior**

**Screenshots**
See below

**Environment (please complete the following information):**
Lens: 5.3.2-latest.20211201.1
Electron: 13.6.1
Chrome: 91.0.4472.164
Node: 14.16.0
© 2021 Mirantis, Inc.

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
![Screenshot 2021-12-09 at 16 18 56](https://user-images.githubusercontent.com/5508278/145413336-f6ecfd04-5ea9-4311-ad89-a700707a5ffd.png)


**Additional context**
Can connect to cluster with command line and with k9s.
6 other clusters connecting perfectly.. Just one cluster producing this error.

**Comment by Nokel81** [comment] 2021-12-09 17:01
Duplicate of https://github.com/lensapp/lens/issues/4506

**Closed by Nokel81** 2021-12-09 17:01 UTC
Labels: bug
