### ISSUE TITLE
Cannot open shell to Windows pods controlled by a statefulset.

### ISSUE THREAD

**Issue by Cova** [lensapp/lens#1056] opened 2020-10-08 18:05 UTC
**Describe the bug**
When trying to open a shell to a Windows pod controlled by a statefulset, the OS detection is failing and it is trying to launch a bash | ash | sh shell, which obviously fails.  Opening shells on other Windows pods that are controlled by deployments/replicasets works properly and opens a powershell inside the container.

**To Reproduce**
Select a pod that is managed by a statefulset - click the 3-dots button and select 'Shell'
Watch error appear:

exec kubectl exec -i -t -n elastic elastic-2 -c elasticsearch "--" sh -c "clear; (bash || ash || sh)"
container b213132bf22f95870da76bbe7c91adcbb4f75da947ef8eb2ef77ab16553f962c encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified.

**Expected behavior**
After selecting 'Shell', briefly see an 'exec kubectl ....' command to run powershell (too fast for me to copy/paste), and then get the powershell terminal for the container.

**Screenshots**
A picture of the error message I pasted above would just use more bytes for the same message...

**Environment (please complete the following information):**
- Lens Version: 3.6.7
- OS: Fedora Linux - also tested by a co-worker on a Windows 10 desktop.
- Installation method: AppImage
 
**Logs:**
No logs appear on the command line from this bug.  Before failing to open a shell, the last log is:
info: [CLUSTER]: refresh {"id":"d620fc45-430c-4503-93d0-3d3e9e7e3683","name":"<redacted>","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}

No new lines appear despite triggering the bug multiple times.

**Comment by Nokel81** [comment] 2021-09-23 20:09
I don't think is related to it being controlled by a statefulset. Marking this as a duplicate of #2823 (even though this is older)

**Closed as completed by Nokel81** 2021-09-23 20:09 UTC
Labels: bug
