### ISSUE TITLE
Opening a shell to a container fails due to bad powershell command

### ISSUE THREAD

**Issue by glennsills** [lensapp/lens#385] opened 2020-05-21 13:16 UTC
**Opening a shell to a container fails due to bad powershell command**

1. Go to 'workloads pods'
2. Click on a pod you want to shell into
3. From either the "..." menu in the list or the menu on the pod detail screen select shell
4. See this error below
PS C:\Users\glenn.sills> exec kubectl exec -i -t -n default svc-tasksscheduler-6dd4fbcccd-rv2hc -c svc-tasksscheduler "--" sh -c "clear; (bash || a
sh || sh)"
exec : The term 'exec' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ exec kubectl exec -i -t -n default svc-tasksscheduler-6dd4fbcccd-rv2h ...
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (exec:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Expected behavior**
kubectl exec -i -t -n default svc-tasksscheduler-6dd4fbcccd-rv2hc -c svc-tasksscheduler sh
works

**Screenshots**
![image](https://user-images.githubusercontent.com/5719647/82562565-79650880-9b43-11ea-8cd1-647dc91c8679.png)

**Environment (please complete the following information):**
- Lens Version: 3.4.0
- OS: Windows 10 Enterprise build 1903
- Installation method (e.g. snap or AppImage in Linux):  Automated update from a previous build

**Comment by kaceo** [comment] 2020-05-25 10:16
I have a similar situation, I am on Windows 10 desktop connecting to a cluster of two Linodes.  I can reach the container shell from executing "kubectl exec ... " inside Powershell.  But inside Lens, using the UI to open the shell just gives an endless "Connecting ..." message.

**Comment by ltrenkner** [comment] 2020-05-26 09:29
I see the same behavior on Win 10 PRO, unneeded exec is added for powershell command in front of actual kubectl command, it seems 6d4a7f657d12d367fb893e8a37aec3c0bbf4faea **Terminal dock tab improvements (#294)** was supposed to fix this issue, but apparently it does not work correctly...

**Comment by santasub** [comment] 2020-05-28 08:15
Same here.

**Comment by msaum** [comment] 2020-05-28 16:49
Same issue here.

**Comment by jakolehm** [comment] 2020-06-04 05:48
Duplicate of #338

**Closed as completed by jakolehm** 2020-06-04 05:48 UTC
Labels: bug, area/windows
