### ISSUE TITLE
Make the auto-update toggable (enable/disable)

### ISSUE THREAD

**Issue by kad-poelw** [lensapp/lens#92] opened 2019-11-22 14:50 UTC
**What would you like to be added**:
An option to enable/disable the auto-update. 

**Why is this needed**:
Currently, as experienced with a bug in 2.6.2, the previous version which was working, is auto-updated to the new one, breaking it. When installing an older version again (like 2.5.3 or 2.6.0), the popup shows it will auto-update the app after you close it, effectively breaking the app again, until to such time the 2.6.2 bug is resolved

**Environment you are Lens application on:**
remote Azure Kubernetes
Local Win10 Docker Desktop + Kubernetes

**Comment by miskun** [comment] 2019-11-22 14:59
I can confirm we have been getting quite few requests for this feature. I think we'll try to make this option available very soon.

**Comment by andrejonathan** [comment] 2019-11-24 05:55
This is a great feature if the testing before release was 100% but as we all know is almost impossible to achieve. Perhaps a happy medium would be to just prompt the user regarding the available upgrade and allow user to skip this version or skip this version until x weeks old and no major bugs reported. The last options would pull directly from your github issue and perform the bug checking logic. Overkill indeed but what fun

**Comment by renaudhager** [comment] 2020-11-21 16:08
Any news about this? It's 1 year old ^^.

**Comment by miskun** [comment] 2020-11-22 07:30
It's very valid issue still. It's not decided yet but I feel this will be
implemented for 4.1

**Comment by pricehatfield** [comment] 2020-12-07 22:45
4.0.0 blew up my Mac today on an automatic update.  Kernel panics every time the window got focus, and again when trying to kill the process.  It somehow ended up in my startup too, so even restarting without opening "currently open apps" wasn't a clean recovery either.  It wasn't pretty.  

Not being able to opt out of updates like this will drive down adoption.

**Comment by pop4959** [comment] 2020-12-08 01:01
Yeah performance on 4.0 is absolutely atrocious. Can barely do anything because the whole UI stalls for even minutes at a time. I'm fairly disappointed that there is not an option to avoid auto updating as the last version was very stable.

**Comment by Win32Sector** [comment] 2020-12-08 13:09
@pricehatfield I faced with the same beheivor today. 
And new version of Lens isn't compatible with cisco anyconnect.
If both lens 4.0.0 and cisco anyconnect installed, system crashes when Lens starts.

**Comment by renaudhager** [comment] 2020-12-09 13:35
Each new version brings new features but also lot of bugs. We still cannot disable auto update.
IMO that should the 1st task to work on, for the sake of the users, it's very annoying to have somehting that works and all the sudden it's broken.
Especially when this issue is more than a year old...

**Comment by lgmorand** [comment] 2021-01-19 07:37
I'm curious. When is triggered auto-update ? For instance, I 'm stuck on 4.0.4 and it never update it. When does it occur ?

**Comment by Nokel81** [comment] 2021-02-10 13:13
Fixed in #1941

**Closed as completed by Nokel81** 2021-02-10 13:13 UTC
Labels: enhancement, blocker
