### ISSUE TITLE
Release 4.0.1

### ISSUE THREAD

**Issue by reddyfull** [lensapp/lens#1738] opened 2020-12-10 15:38 UTC
**Describe the bug**
With the new release of 4.0.1, we dont see any more logs icon on pod.  Is there anyway we can see the logs please.

**Comment by arifiqbal81** [comment] 2020-12-10 19:45
I am also facing this issue  and is a major inconvenience.  Kindly help to fix this issue

**Comment by jakolehm** [comment] 2020-12-11 08:05
Duplicate of #1690

**Closed as completed by jakolehm** 2020-12-11 08:05 UTC
Labels: bug
