### ISSUE TITLE
Shift+Click not working anymore in navigator / Multiple windows or views support 

### ISSUE THREAD

**Issue by MatthieuCoder** [lensapp/lens#996] opened 2020-09-29 09:23 UTC
**Describe the bug**
Hi! 

In the past, i was using Shift+Click to open a new lens window in the browser, it was very useful when viewing multiple ressources at the same time, but since the last version, the browser version is not working

**To Reproduce**
1. Click on any link while pressing shift

**Expected behavior**
A simple lens window wihind the navigator

**Screenshots**
![image](https://user-images.githubusercontent.com/20992787/94539813-c88c1a00-0256-11eb-90ac-e84469f9b743.png)

**Environment (please complete the following information):**
- Lens Version: 3.6.4
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): Installer file and auto updates
 
**Logs:**
See in the screenshot

**Comment by brtasavpatel** [comment] 2020-10-02 23:11
I am facing same issue.
![image](https://user-images.githubusercontent.com/38225409/94976476-f7f68d00-04c9-11eb-9f67-2cb2d550cb69.png)

**Comment by brtasavpatel** [comment] 2020-10-29 23:05
any updates on the fix for this anyone?

**Comment by MatthieuCoder** [comment] 2020-11-06 16:20
that's sad...

**Comment by nevalla** [comment] 2020-11-09 07:22
Cluster dashboard integrates now more on Electron framework and it has broke the compatibility with running cluster dashboard in a browser. I don't see this is very easy to fix without losing some other features that cluster dashboard is now having. So, the issue is that you would like to see multiple resource at the same time. Just thinking how Lens app itself could support this better. I'm open to any ideas since I can see this is very handy feature to you.

**Comment by MatthieuCoder** [comment] 2020-11-15 17:29
@nevalla Then we need a feature to view differents ressources with differents windows, because sometimes we need to see multiple ressources this way (roles & service accounts for exemple) this would be very useful anyways. Currently i'm forced to open lens two times to do what i want and it's pretty annoying to have many connexions :/

**Comment by brtasavpatel** [comment] 2020-11-16 19:41
I also tried downgrading to `v3.5.3` but somehow it didn't work in that version also.

**Comment by Nokel81** [comment] 2021-03-24 19:40
Closing in favour of #521 as I don't think we will be attempting to decouple our reliance on electron.

**Closed as completed by Nokel81** 2021-03-24 19:40 UTC
