### ISSUE TITLE
Show IngressClass resource

### ISSUE THREAD

**Issue by kferrone** [lensapp/lens#3675] opened 2021-08-25 19:53 UTC
**What would you like to be added**:
A new section under `Network` for the `IngressClass` resource. 

**Why is this needed**:
Lens currently does not show IngressClass gui or dashboard of any sort. Would be nice to use lens to view and/or manage my IngressClasses

**Comment by jim-docker** [comment] 2021-08-30 12:47
Duplicate of #2576

**Closed as completed by jim-docker** 2021-08-30 12:47 UTC
Labels: enhancement
