### ISSUE TITLE
Improve ClusterRole display 

### ISSUE THREAD

**Issue by vshakirova** [lensapp/lens#3429] opened 2021-07-19 15:45 UTC
**What would you like to be added**:
Make clusterRole "Rules" section readable
![Screenshot from 2021-07-19 17-51-18](https://user-images.githubusercontent.com/38247153/126187272-53ca200d-3cfb-48cf-a2d2-5c2f88288061.png)
maybe in the same way as Role->Rules 
![Screenshot from 2021-07-19 17-51-34](https://user-images.githubusercontent.com/38247153/126187678-d964e159-5f38-406f-9b6e-1b11dd6cd820.png)

**Why is this needed**:
for readability purposes

**Environment you are Lens application on:**

- Kubernetes distribution: minikube
- Desktop OS: macos

**Comment by Nokel81** [comment] 2021-07-19 19:36
I am marking this as a bug since it is a regression from #2755

**Closed as completed** 2021-07-20 04:40 UTC
Labels: bug
