### ISSUE TITLE
Preserve search result when switching tabs 

### ISSUE THREAD

**Issue by goldlil** [lensapp/lens#2674] opened 2021-04-29 12:30 UTC
**What would you like to be added**:
When switching tabs in lens, eg from deployment to pods I think it would be nice to preserve search entry from previous tab when we returns to it.

**Why is this needed**:
This would make whole experience better and when switching tabs we would not need to reenter last search again.

**Environment you are Lens application on:**
MacOS Catalina, EKS

**Comment by Nokel81** [comment] 2021-12-13 15:11
Duplicate of https://github.com/lensapp/lens/issues/3510

**Closed as completed by Nokel81** 2021-12-13 15:11 UTC
Labels: enhancement
