### ISSUE TITLE
Lens not responding after close terminal

### ISSUE THREAD

**Issue by rdeavila** [lensapp/lens#234] opened 2020-04-09 17:54 UTC
**Describe the bug**
After use the terminal to connect to a pod, I click on `x` icon to close it. When I do it, 

**To Reproduce**
1. Go to 'Workloads > Deployments'
1. Click on an deployment
1. When the right panel open, click on a pod
1. Click on 'pod shell' button
1. Wait the connection
1. Do something (useful or not)
1. Type 'exit' to exit the pod shell
1. Click the Close button, to close the terminal tab
1. Lens freezes

**Expected behavior**
Just close the terminal tab

**Environment (please complete the following information):**
- Lens Version: 3.2.0
- OS: Win10
- Installation method (e.g. snap or AppImage in Linux): Installer
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://REDACTED
  name: gke_mailtop-com-br_us-east1-c_mailtop-k8s
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://REDACTED
  name: gke_mailtop-com-br_us-east1_mailtop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-for-desktop
- context:
    cluster: gke_mailtop-com-br_us-east1-c_mailtop-k8s
    user: gke_mailtop-com-br_us-east1-c_mailtop-k8s
  name: gke_mailtop-com-br_us-east1-c_mailtop-k8s
- context:
    cluster: gke_mailtop-com-br_us-east1_mailtop
    user: gke_mailtop-com-br_us-east1_mailtop
  name: gke_mailtop-com-br_us-east1_mailtop
current-context: gke_mailtop-com-br_us-east1-c_mailtop-k8s
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: gke_mailtop-com-br_us-east1-c_mailtop-k8s
  user:
    auth-provider:
      config:
        access-token: REDACTED
        cmd-args: config config-helper --format=json
        cmd-path: C:\Users\rodrigo\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd
        expiry: "2020-04-04T22:56:13Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: gke_mailtop-com-br_us-east1_mailtop
  user:
    auth-provider:
      config:
        access-token: REDACTED
        cmd-args: config config-helper --format=json
        cmd-path: C:\Users\rodrigo\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd
        expiry: "2020-01-29T17:49:38Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

**Comment by doryanmzr** [comment] 2020-04-21 08:39
same issue for me on win10

**Comment by jbliao** [comment] 2020-04-23 18:00
Same for me with Lens version 3.3.1 on Windows 10 build 18363.778

**Comment by jtackaberry** [comment] 2020-05-03 22:44
I've experienced this since first trying Lens (circa 3.0).  Also Windows 10 1909 (build 18363.778).  The hang occurs several seconds after closing the shell, but it's reliably repeatable.

Poking around with Process Explorer, I see the stack below consistently.  It occurs on the busiest thread and corresponds to when instant Lens hangs.  I find the thread using the most CPU, dump the stack, close the terminal in Lens, and keep refreshing the stack.  About 5-7 seconds later, the stack updates to below and then Lens freezes.

```
ntdll.dll!NtWaitForSingleObject+0x14
KERNELBASE.dll!WaitForSingleObjectEx+0x93
KERNELBASE.dll!ResizePseudoConsole+0xb1
KERNELBASE.dll!ResizePseudoConsole+0x2a
KERNELBASE.dll!ClosePseudoConsole+0xe
KERNEL32.DLL!ClosePseudoConsole
Lens.exe!v8::External::Value+0x72
Lens.exe!std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+0x13bb15
Lens.exe!std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+0xedffd
Lens.exe!std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+0xed51f
Lens.exe!std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+0xed177
Lens.exe!v8_inspector::V8ContextInfo::executionContextId+0x2f6a2d
Lens.exe!v8_inspector::V8ContextInfo::executionContextId+0x274bdc
Lens.exe!v8_inspector::V8ContextInfo::executionContextId+0x2c5d02
Lens.exe!v8_inspector::V8ContextInfo::executionContextId+0x292d32
Lens.exe!v8_inspector::V8ContextInfo::executionContextId+0x27241c
Lens.exe!v8::Unwinder::PCIsInV8+0x325
Lens.exe!v8::Unwinder::PCIsInV8+0xa3f
Lens.exe!v8::Unwinder::PCIsInV8+0x1a681
Lens.exe!node::InternalCallbackScope::Close+0x114
Lens.exe!node::InternalCallbackScope::~InternalCallbackScope+0xd
Lens.exe!node::EmitAsyncDestroy+0xb34fa9
Lens.exe!uv_timer_again+0xb8
Lens.exe!uv_run+0xb2
Lens.exe!uv_loop_delete+0x1651
Lens.exe!uv_cond_signal+0x2d80
Lens.exe!uv_cond_signal+0x11ef6
Lens.exe!uv_cond_signal+0x11b9c
Lens.exe!uv_loadavg+0xd15e4
Lens.exe!uv_loadavg+0xd0ebe
Lens.exe!uv_cond_signal+0x127b6
Lens.exe!uv_os_getpid+0x1056e
Lens.exe!v8::String::Value::operator*+0x13f1e1
Lens.exe!v8::String::Value::operator*+0x13f043
Lens.exe!v8::String::Value::operator*+0x140981
Lens.exe!v8::String::Value::operator*+0x13c51d
Lens.exe!v8::String::Value::operator*+0x505a6
Lens.exe!v8::String::Value::operator*+0x51074
Lens.exe!v8::String::Value::operator*+0x50d1e
Lens.exe!IsSandboxedProcess+0x31f7a
Lens.exe!v8::String::Value::operator*+0x50516
Lens.exe!Ordinal0+0x13bf
Lens.exe!node::AsyncResource::CallbackScope::CallbackScope+0x3dab82
KERNEL32.DLL!BaseThreadInitThunk+0x14
ntdll.dll!RtlUserThreadStart+0x21
```

**Comment by jllew5** [comment] 2020-05-15 12:51
Confirmed same behavior on Windows 10 18362.836, Lens v3.4.0

**Comment by jtackaberry** [comment] 2020-06-05 14:00
I don't think 3.5.0-beta1 was expected to address this, but I figured I'd mention anyway that the issue persists.   (Windows 10 x64 1909 18363.836)

**Closed as completed** 2020-06-09 10:16 UTC
Labels: bug, area/windows

**Comment by tfriedel** [comment] 2021-11-28 23:08
I still have this problem in Windows 10 / Lens 5.3.0-latest.20211125.2

**Comment by george2asenov** [comment] 2021-12-03 07:56
Me and my colleague  also have the same issue. With the latest version. I also fully deleted and reinstalled Lens and the issue persists.

**Comment by khoatdvo** [comment] 2021-12-13 07:22
Got the same issue on windows 10, lens 5.3.2
