### ISSUE TITLE
lens stays open, not visible in cmd+tab

### ISSUE THREAD

**Issue by matti** [lensapp/lens#2075] opened 2021-02-03 08:34 UTC
![2021-02-03 at 10 33](https://user-images.githubusercontent.com/3893/106719714-4f893e80-660b-11eb-88d7-f7e874f0fc78.jpg)

alt+tab does not show it

**Comment by jim-docker** [comment] 2021-02-16 14:46
Hi, what's the context? I see this behaviour when the Lens window is closed but Lens is still active (in the tray). Seems consistent with other apps (like docker desktop)

**Comment by Nokel81** [comment] 2021-03-25 18:02
Duplicate of #1906

**Closed as completed by Nokel81** 2021-03-25 18:02 UTC
Labels: bug
