### ISSUE TITLE
Lens Extension examples don't actually work with Lens.

### ISSUE THREAD

**Issue by benlesh** [lensapp/lens#3474] opened 2021-07-21 17:33 UTC
I have tried the following:

1. Use the yeoman-based generator. I didn't get far with this approach. It seemed to create things that were a little out of date or assumed I wasn't on a Windows machine. (sadly, I'm stuck with a Windows machine for this particular project)

2. Following the instructions for the "Hello World" example found here: https://github.com/lensapp/lens-extension-samples/tree/79ee051064f537bea5eac6734b21491149ad9d6e/helloworld-sample

   - The example itself built and everything, however it was listed as **Incompatible** in the Lens app. With no other information given for me to take action on.
   - I checked the version of Lens, it was `5.1.1-latest.20210716.1`. The version of `@k8slens/extensions` in the `package.json` was only `4.*`, so I updated it to `@latest`, bring it it to `@k8slens/extensions@5.1.2`. I also updated `@types/react` to `17` and `typescript` to latest.
   - I then went about updating the code in the extension to the new export schema, which is namespaced under `Renderer`, `Main`, etc.
   - I uninstalled the old extension, set up a new symlink, and rebuilt the new extension. I ensured that the proper files were in `~/.k8slens/extensions`. Then I restarted the Lens app.
   
Same result:

![image](https://user-images.githubusercontent.com/1540597/126533399-98a730d5-f03c-4ee8-bb7e-e9fb75ab2e8d.png)

As of right now, I'm totally dead in the water trying to figure out how to extend this application. I'm going to have to start digging through code, or perhaps fork another, much more complicated extension project that I know works. No idea if I'll have any luck down those paths.

**Comment by Nokel81** [comment] 2021-07-21 20:48
Actually this is a duplicate of https://github.com/lensapp/lens/issues/2492

**Closed as completed by Nokel81** 2021-07-21 20:48 UTC
Labels: area/extension, area/documentation, blocker

**Comment by benlesh** [comment] 2021-07-21 21:37
haha. why close the one with descriptive information in favor of the one with just a URL? I realize a maintainer made the other one, but people aren't going to find that other one in a search of open issues (I know I didn't).
