### ISSUE TITLE
A JavaScript Error Occured in The Main Process

### ISSUE THREAD

**Issue by brianpham** [lensapp/lens#3253] opened 2021-07-02 15:17 UTC
**Describe the bug**
The bug seems to happens when I have Lens open and close my laptop and reopen my laptop. I get the following error. 

```
A Javascript error occured in the main process. 

Uncaught Exception:
Error: EACCES: permission denied, open '/Users/brianpham/.kube/config.lock'
```

**To Reproduce**
1. Go to Lens
2. Close Mac laptop lid
3. Wait a few mins and repo. 
4. The error should show up when opening back up. 

**Expected behavior**
Nothing should happen. Lens should still be connected to the cluster or say failed to connect to cluster if no longer on VPN. 

**Screenshots**
<img width="262" alt="Screen Shot 2021-07-02 at 8 14 50 AM" src="https://user-images.githubusercontent.com/5695495/124295654-f405a300-db0d-11eb-8e38-76a8b3e6ba97.png">

**Environment (please complete the following information):**
- Lens Version: Lens: 5.0.0-latest.20210629.3
- OS: OSX

**Comment by nevalla** [comment] 2021-07-03 13:07
Duplicate of #3248

**Closed as completed by nevalla** 2021-07-03 13:07 UTC
Labels: bug
