### ISSUE TITLE
Unnecessary failed cluster polling

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#3522] opened 2021-07-28 13:12 UTC
If cluster is selected from the hotbar and connection is failing, it keeps trying to connect one even you moved to other cluster or some different page.

To reproduce:
1. Try to open cluster which connection is failed.
2. Open another connected cluster, work with it for some time (10 seconds)
3. Watch how repeated messages appear with some interval

```
error: Failed to connect cluster "foo": StatusCodeError: 502 - undefined
```

![failed cluster](https://user-images.githubusercontent.com/9607060/127327828-67ab5977-6fc4-4626-b698-ba9dd45c3a44.png)

**Comment by Nokel81** [comment] 2021-11-09 20:32
Are you sure it takes only 10s for this to occur? Because if it takes 30s then it could just be that a cluster tries to refresh its connection status every 30s

**Comment by Nokel81** [comment] 2022-08-04 19:04
Closing as this is actually working as intended.

**Closed as not planned by Nokel81** 2022-08-04 19:04 UTC
Labels: bug
