### ISSUE TITLE
TypeError: Cannot read property 'showTimestamps' of undefined in 4.2.2

### ISSUE THREAD

**Issue by sgametrio** [lensapp/lens#2616] opened 2021-04-24 06:58 UTC
**Describe the bug**
After refreshing the view with <kbd>Ctrl + R</kbd> I got the error page in the screenshot.

**Expected behavior**
It should have refreshed normally

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:4.2.2
- OS: Ubuntu
- Installation method (e.g. snap or AppImage in Linux): AppImage

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Component stack:


    at VD (http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:8293011)
    at div
    at div
    at $D (http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:8299182)
    at footer
    at div
    at Jz (http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:8504731)
    at cc (http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:7679838)
    at t (http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:223892)
    at $z (http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:8506235)

Error stack:

 
TypeError: Cannot read property 'showTimestamps' of undefined
    at VD.renderResourceSelector (http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:8293833)
    at VD.render (http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:8294348)
    at Ce (http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:13973)
    at http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:7555080
    at ce (http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:12079)
    at e.track (http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:23443)
    at VD.s [as render] (http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:7555028)
    at VD.Ee (http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:7555176)
    at VD.t.render (http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:7554132)
    at _s (http://e4ab8ef1-a949-4439-99d1-d5195ee7f193.localhost:34011/build/Lens.js:2:4654529)
```

**Comment by Nokel81** [comment] 2021-04-26 13:11
Duplicate of #2458

**Closed as completed by Nokel81** 2021-04-26 13:11 UTC
Labels: bug
