### ISSUE TITLE
Add refresh button or indicator

### ISSUE THREAD

**Issue by adammw** [lensapp/lens#2070] opened 2021-02-03 01:12 UTC
**What would you like to be added**:
A refresh button and/or indicator of how fresh/stale the information is. For example when clicking into a pod or node and interacting with it outside of lens, I want to force a refresh to ensure i'm viewing the latest data.

**Why is this needed**:
Watching sometimes doesn't work, may be too slow, or there might be items cached (the part i was looking at in particular was a pod's assigned node's taints)

**Environment you are Lens application on:**

- Kubernetes distribution: Custom, K8s 1.19
- Desktop OS: macOS 10.15.7

**Comment by fksimon** [comment] 2021-03-12 19:57
I have also noticed that occasionally when I have deleted all content under an entry like configmaps, pods, etc it will often show stale state with old terminated pods.   Running kubectl get <> returns empty list, but lens keeps showing.   A way to force refresh would be VERY helpful.

**Comment by Nokel81** [comment] 2021-03-25 18:04
Duplicate of #1126. Though if you have a specific example, a new issue with logs and a video would be great.

**Closed as completed by Nokel81** 2021-03-25 18:04 UTC
Labels: enhancement
