### ISSUE TITLE
Hope to hide managedFileds and status in edit mode

### ISSUE THREAD

**Issue by arashicage** [lensapp/lens#3778] opened 2021-09-11 03:12 UTC
What about add buttons to switch visibility of managedFiled and status in edit mode, just like: 

![image](https://user-images.githubusercontent.com/5427687/132934201-83b00efd-b6df-47d1-9cdf-adb65abd8dde.png)

**Comment by Nokel81** [comment] 2021-09-13 13:53
Hello thanks for the report. This is a duplicate of #2765. This is a very good thing to have.

**Closed as completed by Nokel81** 2021-09-13 13:53 UTC
Labels: enhancement
