### ISSUE TITLE
Lens crashed after refresh of AWS credentials

### ISSUE THREAD

**Issue by asankov** [lensapp/lens#2921] opened 2021-05-31 17:20 UTC
**Describe the bug**
I got a crash after refreshing my AWS credentials.

**To Reproduce**
Not sure how to give you the proper steps, but here is my workflow:
1. I use an EKS cluster and I connect to that with rolling credentials, e.g. I don't have permanent credentials to it, I get credentials via `saml2aws`. These credentials expire every hour at which point I see `Invalid connection` error in Lens. After I run `saml2aws` and obtain new credentials, I go to Lens, hit "Refresh" and the connection is restored.

Today I did just that, but instead I got an error screen:
![image](https://user-images.githubusercontent.com/18421997/120224928-05c50380-c24d-11eb-83ae-859f04ae1ff6.png)

Here are the stack traces in copy-pasteable manner:
```
Component stack:


    at KD (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:8296788)
    at div
    at tF (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:8302823)
    at div
    at div
    at cF (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:8308806)
    at footer
    at div
    at pU (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:8514060)
    at cc (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:7683374)
    at t (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:223994)
    at BU (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:8515564)
```

```
Error stack:

 
TypeError: Cannot read property 'showTimestamps' of undefined
    at KD.get logs (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:8299041)
    at ce (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:12079)
    at e.computeValue (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:18380)
    at e.trackAndCompute (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:18206)
    at e.get (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:17257)
    at e.read (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:51873)
    at KD.get (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:53326)
    at KD.render (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:8299148)
    at Ce (http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:13973)
    at http://1b52f9c0-69d9-44d9-80b4-5c50f6e41396.localhost:49284/build/Lens.js:2:7558683
```

**Expected behavior**
Not crash, but restore the cluster view after the credentials are refreshed and valid.

**Environment (please complete the following information):**
- Lens Version: 4.2.4
- OS: [e.g. OSX] 11.3.1

I can provide more info if needed.

This is the first time I experience this and it is a really minor problem. I won't mind if you close this as a non-reproduce-able or something like this.

Overall, the product is great and it is a big part of my workflow. Kudos for the good work.

**Comment by Nokel81** [comment] 2021-06-01 19:33
Duplicate of https://github.com/lensapp/lens/issues/2652

**Closed as completed by Nokel81** 2021-06-01 19:33 UTC
Labels: bug
