### ISSUE TITLE
Lens crashes every now and then

### ISSUE THREAD

**Issue by arfatbk** [lensapp/lens#1779] opened 2020-12-15 07:46 UTC
**Description**
Lens keeps crashing so often. Only way is to reconnect to cluster. "Back" button is doing no help.

**To Reproduce**
1. Click on sub-menus

sometimes it woks , sometimes it crashes

**Expected behavior**
IDE should be able to catch exceptions/errors and handle them gracefully. Just a notification about error to user will be fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/24441176/102185653-66e35f80-3ed7-11eb-87d0-e5a2c2e118ed.png)

**Environment (please complete the following information):**
- Lens Version: 4.0.2
- OS: [e.g. Windows]
- Installation method (e.g. snap or AppImage in Linux): setup.exe

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Error stack:
TypeError: Cannot read property 'kind' of undefined
    at r.value (http://cb63d63f-69d6-4ffd-84bc-046b92d2ae62.localhost:60718/build/Lens.js:2:3775674)
    at http://cb63d63f-69d6-4ffd-84bc-046b92d2ae62.localhost:60718/build/Lens.js:2:8681250
    at Array.map (<anonymous>)
    at http://cb63d63f-69d6-4ffd-84bc-046b92d2ae62.localhost:60718/build/Lens.js:2:8681218
    at Array.map (<anonymous>)
    at r.value (http://cb63d63f-69d6-4ffd-84bc-046b92d2ae62.localhost:60718/build/Lens.js:2:8681162)
    at r.value (http://cb63d63f-69d6-4ffd-84bc-046b92d2ae62.localhost:60718/build/Lens.js:2:8686510)
    at ve (http://cb63d63f-69d6-4ffd-84bc-046b92d2ae62.localhost:60718/build/Lens.js:2:18448)
    at http://cb63d63f-69d6-4ffd-84bc-046b92d2ae62.localhost:60718/build/Lens.js:2:70625
    at ce (http://cb63d63f-69d6-4ffd-84bc-046b92d2ae62.localhost:60718/build/Lens.js:2:16554)
```

**Comment by nevalla** [comment] 2020-12-15 07:57
Is this happpening only when the target cluster is Kubernetes 1.20?

**Comment by dangear** [comment] 2020-12-15 16:20
same problem on MacOS 10.15.7, Kubernetes 1.20, Lens 4.0.3

**Comment by nevalla** [comment] 2020-12-16 08:12
Duplicate of #1711. Let's monitor the resolution on that issue.

**Closed as completed by nevalla** 2020-12-16 08:12 UTC
Labels: bug, duplicate

**Comment by arfatbk** [comment] 2020-12-18 17:11
I noticed this is only happening with kubernets version 1.20.0
tested on version 1.17.1. Works like charm.

Also in version 1.20.0, the drill-down menus are not appearing(the pop-up from right side)
Duplicate of #1711
