### ISSUE TITLE
App crash at /cluster, Cannot read property 'containers' of undefined

### ISSUE THREAD

**Issue by SovakPaleny** [lensapp/lens#3378] opened 2021-07-14 12:27 UTC
**Describe the bug**
Azure AKS cluster, opened a list of pods, recreated some pods, and opened logs of removed pod/container. I'm unable to open the cluster anyhow. 
**To Reproduce**
- open a cluster
- error is shown

**Expected behavior**

**Screenshots**
```
 TypeError: Cannot read property 'containers' of undefined
    at pods_api_Pod.getContainers (http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:502788:26)
    at http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:529205:28
    at http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:471291:49
    at http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:471255:25
    at trackDerivedFunction (http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:1881:18)
    at Reaction.track (http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:2409:18)
    at useObserver (http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:471253:14)
    at http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:471291:16
    at Ch (http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:442361:137)
    at li (http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:442384:154)
    at ki (http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:442382:169)
    at ii (http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:442381:178)
    at ck (http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:442478:126)
    at bk (http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:442454:347)
    at ak (http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:442454:278)
    at Tj (http://2523486b895c5d47d44ef254e28fbbbd.localhost:61571/build/Lens.js:442454:138)
```

**Environment (please complete the following information):**
- Lens Version: 5.0.2-latest.20210705.2
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): DMG

**Additional context**
Lens 4 was able to recover after deleting cluster configuration, this doesn't work with lens 5

**Comment by Nokel81** [comment] 2021-07-14 12:28
Duplicate of #2854

**Closed as completed by Nokel81** 2021-07-14 12:28 UTC
Labels: bug
