### ISSUE TITLE
How to add cluster

### ISSUE THREAD

**Issue by yThomasS** [lensapp/lens#3499] opened 2021-07-23 12:24 UTC
**Describe the bug**
Clicking on "Add cluster" opens a page. But it is not clear what/how to add a kubeconfig here

**To Reproduce**
1. Go to 'Add cluster'

**Expected behavior**
In version 4 there was the possibility to select a kubeconfig.

**Screenshots**

**Environment (please complete the following information):**
- Lens: 5.1.3-latest.20210722.1
- OS: [e.g. OSX] macOS 11.4
- Installation method (e.g. snap or AppImage in Linux): upgrade from version 4

**Comment by Nokel81** [comment] 2021-07-23 13:19
This will be fixed by #3234 

For the meantime, you can go to user preferences and add your kubeconfig files to the list of syncs. Sorry that it wasn't more obvious.

**Comment by vchirikov** [comment] 2021-08-03 08:44
~~It doesn't work. I tried to add files/folders to the `Kubeconfig Syncs` section and nothing has changed.~~
Clusters were added to the catalog, and then you can add them to the sidebar.

p.s. In v4 it was very easy.

**Comment by Nokel81** [comment] 2021-08-03 13:21
You can pin clusters by clicking the triple dots in the catalog. In the future we plan to allow drag'n'drop entities to the hotbar (see #2825 )

**Comment by frankmariette** [comment] 2021-08-16 22:18
@Nokel81 Is there a way to use the v4 UI? This new one seems more complicated and I have a harder time finding the clusters I care about. Also adding a new cluster is much more cumbersome than v4 which allowed adding a file. I have to work with a lot of different clusters and I keep configs separated by env and who owns them though this new UI makes it harder to keep that without having to go through the cmd line to do so. At that point I can just use k9s or something else if I have to go to the terminal to fetch this info. Also, having all kubefiles sync is less than ideal as I don't need them all in Lens.

**Comment by Nokel81** [comment] 2021-08-17 18:04
> Clusters were added to the catalog, and then you can add them to the sidebar.

That was chosen so that you can have several hotbars, we are planning to add the ability to add keyboard shortcuts and multiple window support so that swapping between clusters can be done very quickly.

> I have a harder time finding the clusters I care about.

Does having several hotbars (you can create them either by opening up the command-pallet by pressing "Shift+CmdOrCtrl+P" or by clicking on the number at the bottom) not afford enough highlighting?

We are planning on adding support for folders to the catalog in the future so that you can organize any entities (including clusters) there as well.

> Also, having all kubefiles sync is less than ideal as I don't need them all in Lens.

It doesn't cost anything to have them in Lens, and some people find it much more convenient to be able to open Lens and all their clusters are there from the get go.

Furthermore, if you don't want to sync all the files within `~/.kube` you can go and remove that sync

**Closed as completed by Nokel81** 2021-08-17 18:04 UTC
Labels: bug

**Comment by frankmariette** [comment] 2021-08-18 07:50
> Does having several hotbars (you can create them either by opening up the command-pallet by pressing "Shift+CmdOrCtrl+P"
This was more of an issue when this feature went live and was not an opt in though just happened. I went from having 3 clusters which I was actively working with go to 15 or so as it synced in clusters that I had kubeconfigs for that I had only debugged.

>We are planning on adding support for folders to the catalog in the future so that you can organize any entities (including clusters) there as well.
This would be an awesome addition. 

>It doesn't cost anything to have them in Lens, and some people find it much more convenient to be able to open Lens and all their clusters are there from the get go.
I understand there are multiple use cases. I was asking if it is possible to go back to the v4 as an option for users that preferred that workflow for both adding and managing kubeconfigs. The cost I find is the extra time spent trying to find the cluster config I care about which becomes more of a pain when trying to jump between clusters. 

These are just a couple annoyances with the latest changes. Overall Lens is an awesome tool and really appreciate you taking the time to work on it and also to respond to issues. I posted here as the issue is very similar to what I experienced and seemed like a fitting place to provide some feedback. Thanks again for the work and time spent on this project.
