### ISSUE TITLE
connecting... clusters locks up UI

### ISSUE THREAD

**Issue by matti** [lensapp/lens#1757] opened 2020-12-11 15:14 UTC
4.0.1, mac

![image](https://user-images.githubusercontent.com/3893/101920244-3e581e80-3bd4-11eb-915e-fef64bc038da.png)

**Comment by matti** [comment] 2020-12-11 15:14
so like nothing can be clicked, have to quit lens

**Comment by MattFellows** [comment] 2021-02-09 09:55
I get this too - everytime I restart my machine lens refuses to connect to the clusters untill I remove them all and restart lens, then re-add the clusters.  If I leave it too long before I do this, the UI locks up and I have to restart lens, before I can delete all my clusters, and re-add them

MacOS 10.15.7 (Catalina)
Lens: 4.0.8
Electron: 9.3.5
Chrome: 83.0.4103.122
Node: 12.14.1

**Comment by Nokel81** [comment] 2021-03-25 17:03
Is this still happening on 4.1.4? If so, some logs would be useful

**Comment by Nokel81** [comment] 2021-09-23 19:24
Closing as not able to reproduce on any recent version.

**Closed as completed by Nokel81** 2021-09-23 19:24 UTC
Labels: bug, area/macos, area/ui
