### ISSUE TITLE
On Node overview: list of PODs does not show CPU and Memory usage

### ISSUE THREAD

**Issue by ewuknadierf** [lensapp/lens#2771] opened 2021-05-14 06:57 UTC
**Describe the bug**
The list of Pods in the node details for a single node does not visualize the CPU and memory consumption.
Instead errors in Developer Tools occures:
`loadKubeMetrics failed TypeError: Cannot read property 'length' of null`

**To Reproduce**
1. Go to 'Nodes'
2. Click on a single node
3. Scroll down to 'Pods'
4. See all Pods for the node
5. See empty CPU and Memory columns

**Expected behavior**
The columns should show the consumption of CPU and memory for the Pods.

**Screenshots**
Do not find CPU and memory visualisation.
Find error in developer tools.
![image](https://user-images.githubusercontent.com/1555662/118233095-c303dd00-b491-11eb-8a2b-d6113015993a.png)

Find CPU and memory metrics in Pos-Details:
![image](https://user-images.githubusercontent.com/1555662/118233026-ae274980-b491-11eb-9bf5-6d223e83d6f7.png)

**Environment (please complete the following information):**
- Lens Version: 4.2.4
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): 

**Additional context**
Just tried an old version 4.1.4 - and the visualisation for Pods works as expected, and no errors in the devloper tools.
![image](https://user-images.githubusercontent.com/1555662/118234156-4114b380-b493-11eb-8a5e-6c971f082940.png)

**Comment by jim-docker** [comment] 2021-05-17 12:10
Duplicate of #2664 , fixed by #2744 , should be coming in 4.2.5

**Closed as completed by jim-docker** 2021-05-17 12:10 UTC
Labels: bug
