### ISSUE TITLE
Metrics not available on EKS

### ISSUE THREAD

**Issue by zapman449** [lensapp/lens#610] opened 2020-07-23 13:26 UTC
**Describe the bug**
Lens does not show metrics for CPU/Memory/Disk for nodes or pods against an EKS cluster

**To Reproduce**
1. Create EKS cluster
2. Point Lens at cluster
3. Attempt to see node or pod metrics.  There will be a spinner for a few seconds, then ` Metrics not available at the moment`

**Expected behavior**
Show a visualization of the CPU/Memory metrics

**Environment (please complete the following information):**
- Lens Version: 3.5.1
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux):  Brew cask install lens
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
❯ /Applications/Lens.app/Contents/MacOS/Lens
info: Checking for update
info: Update for version 3.5.1 is not available (latest version: 3.5.1, downgrade is disallowed).
warn: PrometheusOperator: failed to list services: [object Object]
warn: PrometheusHelm: failed to list services: [object Object]
warn: PrometheusLens: failed to list services: services "prometheus" is forbidden: User "app-ski-metrics-demo-deployers" cannot get resource "services" in API group "" in the namespace "lens-metrics"
warn: PrometheusHelm: failed to list services: [object Object]
warn: PrometheusLens: failed to list services: services "prometheus" is forbidden: User "app-ski-metrics-demo-deployers" cannot get resource "services" in API group "" in the namespace "lens-metrics"
warn: PrometheusOperator: failed to list services: [object Object]
warn: PrometheusLens: failed to list services: services "prometheus" is forbidden: User "app-ski-metrics-demo-deployers" cannot get resource "services" in API group "" in the namespace "lens-metrics"
warn: PrometheusHelm: failed to list services: [object Object]
warn: PrometheusHelm: failed to list services: [object Object]
warn: PrometheusOperator: failed to list services: [object Object]
info: using lens as prometheus provider
warn: PrometheusLens: failed to list services: services "prometheus" is forbidden: User "app-ski-metrics-demo-deployers" cannot get resource "services" in API group "" in the namespace "lens-metrics"
warn: PrometheusOperator: failed to list services: [object Object]
info: using lens as prometheus provider
```

**Kubeconfig:**
The kubeconfig provided is functional.  For example `kubectl top pod -n <my_namespace>` works

**Additional context**
The context in question is not a cluster-admin context, but rather an "app-admin" context.  It has (mostly) full rights to a single namespace (which is NOT lens-metrics), and limited visibility other namespaces.  It does have access to various metrics objects:

```
  - apiGroups:
    - metrics.k8s.io
    resources:
    - pods
    - nodes
    verbs:
    - get
    - list
    - watch
```

Are the lens-metrics namespace requirements documented somewhere I missed?  google isn't turning up much.

**Comment by zapman449** [comment] 2020-07-23 13:26
FWIW, this might be a dup of https://github.com/lensapp/lens/issues/561

**Comment by nevalla** [comment] 2020-07-30 12:25
`kubectl top` uses metrics-server to display metrics. Lens uses Prometheus. Is the prometheus installed in the cluster?

**Comment by papko26** [comment] 2020-08-27 13:05
I am using this workaround for "app-admin" context. I am using Prometheus-operator deployed in "monitoring" namespace, with instance name "prometheus-k8s", and you can implement workaround in two steps:
1) Create role and role-binding to allow app-admin read data,
```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: app-admin-name-read-monitoring_RB
  namespace: monitoring
subjects:
- kind: User
  name: app-admin-name
  apiGroup: ""
roleRef:
  kind: Role
  name: monitoring_read_R
  apiGroup: ""
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: monitoring
  name: monitoring_read_R
rules:
- apiGroups: ["*"]
  resources: ["*", "pods/log"]
  verbs: ["get", "list", "watch"]
---
```
2) In lens settings set prom address:
```
Prometheus installation method:
Prometheus Operator
```
```
Prometheus service address:
monitoring/prometheus-k8s:9090
```
![pro](https://user-images.githubusercontent.com/25054258/91445681-1809af80-e87f-11ea-8bd7-026e907fea1c.png)

**Comment by chandu484** [comment] 2020-12-11 17:56
Facing similar issue! Any progress on this?

**Comment by VanDerLars** [comment] 2021-01-15 10:26
same here, looking forward for some progress :)

**Comment by Nokel81** [comment] 2021-03-24 17:13
This doesn't seem like a Lens issue, we use Prometheus and not metrics-server. Though #1865 is related. And I am closing this in favour of that.

**Closed as completed by Nokel81** 2021-03-24 17:13 UTC

**Comment by suberjin** [comment] 2024-01-24 09:00
I know that the issue is closed, but since I have faced a similar one and this issue was 1st in Google, I would add some information. 
Please ensure that Prometheus port 9090 is open for the EKS control plane in the security group.
