### ISSUE TITLE
windows aws not found in PATH

### ISSUE THREAD

**Issue by matti** [lensapp/lens#2756] opened 2021-05-12 07:51 UTC
![2021-05-12 at 10 50](https://user-images.githubusercontent.com/3893/117938646-ef8feb80-b30f-11eb-8a29-45b0c88314fd.jpg)

however, in cmd.exe `aws` works.

**Comment by jim-docker** [comment] 2021-05-17 13:02
Did you try the absolute path in the kubeconfig?

**Comment by jim-docker** [comment] 2021-05-17 13:34
duplicate of #2290

**Closed as completed by jim-docker** 2021-05-17 13:34 UTC
Labels: bug
