### ISSUE TITLE
Ctrl+C terminates the shell instead of the command running

### ISSUE THREAD

**Issue by tugtugtug** [lensapp/lens#371] opened 2020-05-13 17:46 UTC
**Environment**
OS: Ubuntu 1804
Lens Version: 3.4.0
Installation Method: snap edge

**Description**
The bug has existed since I started playing with this great tool. And it has becoming a major annoyance whilst using it as my daily driver.

Whenever I use lens to open a shell, be it a pod shell or other shell, whenever I hit Ctrl+C, to terminate the running command, it terminates the entire shell instead, and often leaves a stale process running on the pod that I have to later clean up.

This is currently 100% reproducible, and whenever I hit Ctrl+C, I get the following prompt and the shell is dead.

> Terminal will auto-close in 15 seconds ...

**To Reproduce**
Launch a pod shell, hit CTRL+C

**Expected Behavior**
CTRL+C should act like other shells to terminate the running command within the shell instead of killing the shell itself.

**Comment by Nokel81** [comment] 2022-06-22 18:22
Cannot reproduce this in 5.5.4 on either macOS or linux. Closing.

**Closed as completed by Nokel81** 2022-06-22 18:22 UTC
Labels: bug
