### ISSUE TITLE
Windows JavaScript Error When Opening App as Regular User

### ISSUE THREAD

**Issue by treyhendon** [lensapp/lens#2374] opened 2021-03-23 12:59 UTC
**Describe the bug**
When I open Lens I get a JavaScript error if I do not use "Run As Administrator" Windows Option.

**To Reproduce**
1. Open the Windows Start Menu.
2. Click on Lens item created during installation.
3. See error before application opens.

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: EPERM: operation not permitted, open 'C:\Program Files\Lens\resources\app.asar.unpacked\node_modules\win-ca\pem\roots.pem'
```

**Expected behavior**
The installation should register any needed modules or offer the user the option to "always run as admin" when launching.

**Screenshots**
![image](https://user-images.githubusercontent.com/3513589/112144990-2e2ae480-8bb0-11eb-94f0-6804cbecb033.png)

**Environment (please complete the following information):**
- Lens Version: 4.1.4
- OS: Windows 10 Pro 1909
- Installation method (e.g. snap or AppImage in Linux): Download exe from GitHub Release

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: ≡ƒÜÇ Starting Lens from "C:\Users\myuser\AppData\Roaming\Lens"
info: ≡ƒÉÜ Syncing shell environment
info: ≡ƒÆ╛ Loading stores
info: [STORE]: LOADED from C:\Users\myuser\AppData\Roaming\Lens\config.json
info: [STORE]: LOADED from C:\Users\myuser\AppData\Roaming\Lens\lens-cluster-store.json
info: [STORE]: LOADED from C:\Users\myuser\AppData\Roaming\Lens\lens-workspace-store.json
info: [STORE]: LOADED from C:\Users\myuser\AppData\Roaming\Lens\lens-extensions.json
info: [STORE]: LOADED from C:\Users\myuser\AppData\Roaming\Lens\lens-filesystem-provisioner-store.json
info: ≡ƒöæ Getting free port for LensProxy server
info: [CLUSTER-MANAGER]: init cluster {"id":"07c28589-guid","name":"test-admin","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"32a02624-guid","name":"magic-admin","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"c0af02d1-guid","name":"dev-admin","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"bf6ca885-guid","name":"qa-admin","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"7fd0a581-guid","name":"mgmt-admin","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"3bc618cd-guid","name":"prod-admin","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"78927fd5-guid","name":"uat-admin","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: ≡ƒöî Starting LensProxy
info: [LENS-PROXY]: Proxy server has started at http://localhost:59059
info: ≡ƒöÄ Testing LensProxy connection ...
info: [CLUSTER]: "test-admin" init success {"id":"07c28589-guid","context":"test-admin","apiUrl":"https://host.name:443"}
info: [CLUSTER]: "magic-admin" init success {"id":"32a02624-guid","context":"magic-admin","apiUrl":"https://ip.address:6443"}
info: [CLUSTER]: "dev-admin" init success {"id":"c0af02d1-guid","context":"dev-admin","apiUrl":"https://host.name:443"}
info: [CLUSTER]: "qa-admin" init success {"id":"bf6ca885-guid","context":"qa-admin","apiUrl":"https://host.name:443"}
info: [CLUSTER]: "mgmt-admin" init success {"id":"7fd0a581-guid","context":"mgmt-admin","apiUrl":"https://host.name:443"}
info: [CLUSTER]: "prod-admin" init success {"id":"3bc618cd-guid","context":"prod-admin","apiUrl":"https://host.name:443"}
info: [CLUSTER]: "uat-admin" init success {"id":"78927fd5-guid","context":"uat-admin","apiUrl":"https://host.name:443"}
info: ΓÜí LensProxy connection OK
info: ≡ƒûÑ∩╕Å  Starting WindowManager
info: ≡ƒº⌐ Initializing extensions
info: [EXTENSION-DISCOVERY] loading extensions from C:\Users\myuser\AppData\Roaming\Lens
info: [EXTENSION-INSTALLER] installing dependencies at C:\Users\myuser\AppData\Roaming\Lens
info: [WINDOW-MANAGER]:┬áLoading Main window from url: http://localhost:59059 ...
info: [EXTENSION-INSTALLER] dependencies installed at C:\Users\myuser\AppData\Roaming\Lens
info: [EXTENSION-DISCOVERY] watching extension add/remove in C:\Users\myuser\.k8slens\extensions
info: [EXTENSION]: enabled lens-license@0.1.0
info: [STORE]: LOADED from C:\Users\myuser\AppData\Roaming\Lens\extension-store\lens-survey\preferences-store.json
info: [EXTENSION]: enabled lens-survey@0.1.0
telemetry main extension activated
info: [STORE]: LOADED from C:\Users\myuser\AppData\Roaming\Lens\extension-store\lens-telemetry\preferences-store.json
info: [EXTENSION]: enabled lens-telemetry@0.1.0
info: [CLUSTER]: activate {"id":"07c28589-guid","name":"test-admin","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: bind events {"id":"07c28589-guid","name":"test-admin","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: reconnect {"id":"07c28589-guid","name":"test-admin","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [KUBE-AUTH]: out-channel "kube-auth:07c28589-guid" {"data":"Authentication proxy started\n","meta":{"id":"07c28589-guid","name":"test-admin","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}}
info: [WINDOW-MANAGER]: Main window loaded
info: ≡ƒôí Checking for app updates
info: Checking for update
warn: PrometheusLens: failed to list services: services "prometheus" not found
warn: PrometheusLens: failed to list services: services "prometheus-server" not found
warn: PrometheusLens: failed to list services: services "prometheus-server" not found
warn: PrometheusLens: failed to list services: services "prometheus" not found
info: using helm as prometheus provider
info: Update for version 4.1.4 is not available (latest version: 4.1.4, downgrade is disallowed).
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: devca
    server: https://host.name:443
  name: dev
- cluster:
    certificate-authority-data: dev001
    server: https://host.name:443
  name: dev001
- cluster:
    certificate-authority-data: mgmt.ca
    server: https://host.name:443
  name: mgmt
- cluster:
    certificate-authority-data: nonprod.ca
    server: https://host.name:443
  name: nonprod
- cluster:
    certificate-authority-data: prod.ca
    server: https://host.name:443
  name: prod
- cluster:
    certificate-authority-data: qa.ca
    server: https://host.name:443
  name: qa
- cluster:
    certificate-authority-data: test.ca
    server: https://host.name:443
  name: test
- cluster:
    certificate-authority-data: uat.ca
    server: https://host.name:443
  name: uat
- cluster:
    certificate-authority-data: devk8s.ca
    server: https://ip.address:6443
  name: dev-k8s
- cluster:
    certificate-authority-data: dockerdesktop.ca
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
- cluster:
    certificate-authority-data: magick8s.ca
    server: https://ip.address:6443
  name: magic-k8s
- cluster:
    certificate-authority-data: qak8s.ca
    server: https://ip.address:6443
  name: qa-k8s
contexts:
- context:
    cluster: dev001
    user: clusterUser_dev001
  name: dev
- context:
    cluster: dev001
    user: clusterAdmin_dev001
  name: dev-admin
- context:
    cluster: dev
    user: clusterAdmin_dev
  name: dev-admin
- context:
    cluster: mgmt
    user: clusterAdmin_mgmt
  name: mgmt-admin
- context:
    cluster: nonprod
    user: clusterUser_nonprod
  name: nonprod
- context:
    cluster: nonprod
    user: clusterAdmin_nonprod
  name: nonprod-admin
- context:
    cluster: nonprod
    user: clusterAdmin_nonprod
  name: nonprod-admin
- context:
    cluster: prod
    user: clusterUser_prod
  name: prod
- context:
    cluster: prod
    user: clusterAdmin_prod
  name: prod-admin
- context:
    cluster: qa
    user: clusterAdmin_qa
  name: qa-admin
- context:
    cluster: test
    user: clusterAdmin_test
  name: test-admin
- context:
    cluster: uat
    user: clusterAdmin_uat
  name: uat-admin
- context:
    cluster: dev-k8s
    user: devk8s-admin
  name: dev-admin
- context:
    cluster: dev-k8s
    namespace: codename1
    user: devk8s-admin
  name: dev-admin-codename1
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: magic-k8s
    user: magick8s-admin
  name: magic-admin
- context:
    cluster: magic-k8s
    namespace: codename2
    user: magick8s-automation
  name: magic-codename2-automation
- context:
    cluster: qa-k8s
    user: qak8s-admin
  name: qa-admin
- context:
    cluster: qa-k8s
    namespace: codename1
    user: qak8s-admin
  name: qa-admin-codename1
current-context: dev-admin
kind: Config
preferences: {}
users:
- name: clusterAdmin_dev
  user:
    client-certificate-data: ***
    client-key-data: ***
    token: ***
- name: clusterAdmin_nonprod
  user:
    client-certificate-data: ***
    client-key-data: ***
    token: ***
- name: clusterAdmin_prod
  user:
    client-certificate-data: ***
    client-key-data: ***
    token: ***
- name: clusterAdmin_qa
  user:
    client-certificate-data: ***
    client-key-data: ***
    token: ***
- name: clusterAdmin_test
  user:
    client-certificate-data: ***
    client-key-data: ***
    token: ***
- name: clusterAdmin_uat
  user:
    client-certificate-data: ***
    client-key-data: ***
    token: ***
- name: clusterAdmin_dev001
  user:
    client-certificate-data: ***
    client-key-data: ***
    token: ***
- name: clusterAdmin_mgmt
  user:
    client-certificate-data: ***
    client-key-data: ***
    token: ***
- name: clusterUser_nonprod
  user:
    client-certificate-data: ***
    client-key-data: ***
    token: ***
- name: clusterUser_prod
  user:
    auth-provider:
      config:
        apiserver-id: ***
        client-id: ***
        config-mode: "1"
        environment: publicenv
        tenant-id: ***
      name: someone
- name: clusterUser_dev001
  user:
    auth-provider:
      config:
        access-token: ***
        apiserver-id: ***
        client-id: ***
        config-mode: "1"
        environment: publicenv
        expires-in: "***"
        expires-on: "***"
        refresh-token: ***
        tenant-id: ***
      name: someone
- name: devk8s-admin
  user:
    client-certificate-data: ***
    client-key-data: ***
    token: ***
- name: docker-desktop
  user:
    client-certificate-data: ***
    client-key-data: ***
- name: magick8s-admin
  user:
    client-certificate-data: ***
    client-key-data: ***
    token: ***
- name: magick8s-automation
  user:
    token: ***
- name: qak8s-admin
  user:
    client-certificate-data: ***
    client-key-data: ***
    token: ***
```

**Additional context**
Right-clicking and running as admin does not cause this issue.

**Comment by jim-docker** [comment] 2021-03-29 12:44
Can you try installing Lens in another folder, where you have permissions?

**Comment by treyhendon** [comment] 2021-03-30 16:15
I got an upgrade notification and it failed, so I decided to uninstall and reinstall to custom folder.  I now have version 4.1.5 installed in `C:\lensapp\lens` for all users and do not have to "Run As Administrator".

Seems like the Windows installer needs to set a Windows UAC rule for the Program Files folder or set the exe to always run as admin.

**Comment by jmaerki** [comment] 2021-04-03 07:33
I've got the same problem since I've started using Lens (it's just great!) like 4 or 5 releases ago. I can usually fix it, by giving the ```[..]\resources\app.asar.unpacked\node_modules\win-ca\pem``` directory "Modify" Permissions for the "Users" group. I have to do that after every upgrade where the installer seems to revert back to normal "Read" permission for "Users". I assume the CA certs only really need to be accessed in read-only mode after installation and the "Users" group does have "Read" Permissions. So my assumption is that the ```roots.pem``` file is accessed using a Read/Write mode instead of a Read mode inside normal Lens operation. The latter would probably solve the problem without the need for any custom installation locations or running Lens as Administrator. HTH

**Comment by Nokel81** [comment] 2021-04-26 17:05
Duplicate of #2443

**Closed as completed by Nokel81** 2021-04-26 17:05 UTC
Labels: bug

**Comment by arlllk** [comment] 2021-04-26 17:06
I don't see how this issue relates to #2443

**Comment by Nokel81** [comment] 2021-04-26 17:08
Sorry

duplicate of #2328
