### ISSUE TITLE
Extension child pages in clusterPageMenus get wrong styling

### ISSUE THREAD

**Issue by juv** [lensapp/lens#1902] opened 2021-01-06 09:26 UTC
**Describe the bug**
Hi, I'm facing an issue when adding a page as a child of another page in `clusterPageMenus` like so:
```
    {
      parentId: this.#menuItemParentId,
      target: { pageId: this.#projectsPageId },
      title: "Projects",
      components: {
        Icon: FilterTiltShiftIcon,
      }
    },
```
when I add `parentId: this.#menuItemParentId`, I am seeing that my component is cropped to about 1/3rd of the screen eventhough there are a lot objects to render (> 60 or >100):

when I remove the `parentId: this.#menuItemParentId`, I get the result I intended to render.

**Expected behavior**
The styling to be applied as in a cluster page that is a non-child page.

**Screenshots**
https://i.imgur.com/e5HuoTe.png

**Environment (please complete the following information):**
- Lens Version: 4.0.6
- OS: Windows

**Comment by Nachasic** [comment] 2021-01-29 08:20
Thanks for submitting this issue! Can you provide us with a minimal extension code example that replicates this behavior?

**Comment by juv** [comment] 2021-01-29 13:22
@Nachasic hi, the crucial part is really setting up the field `parentId: this.#menuItemParentId` in the element of `clusterPageMenus`:
Take any of your extensions, then go to `renderer.tsx` and adjust the entries of `clusterPageMenus`: 

```
export function FilterTiltShiftIcon(props: Component.IconProps) {
  return <Component.Icon {...props} material="airplay"/>
} 


  #menuItemParentId = "some-parent-id";
  #routesPageId = "whatever-id";
  clusterPageMenus = [
....,
    {
      id: this.#menuItemParentId,
      title: "Parent",
      components: {
        Icon: FilterTiltShiftIcon,
      }
    },
    {
      parentId: this.#menuItemParentId,
      target: { pageId: this.#routesPageId },
      title: "Routes",
      components: {
        Icon: FilterTiltShiftIcon,
      }
    }
]
```

you would also need something to be rendered in the sub-page so you'll also need to extend the `clusterPages` array as well
```
  clusterPages = [
...,
    {
      id: this.#routesPageId,
      components: {
        Page: () => <RoutePage extension={this} />,
      }
    },
]
```

hope this helps, lmk if you need more information

**Comment by Nokel81** [comment] 2021-07-20 17:09
Further testing shows that if a `clusterPageMenu` item either has child page menus or is a child page menu then the icon does not render.

**Comment by Nokel81** [comment] 2021-07-20 20:37
@juv is this still an issue. From my testing this looks like neither case gets expanded to `height: 100%` without explicit styling.

**Comment by Nokel81** [comment] 2021-08-23 14:36
Closing as I cannot reproduce this

**Closed as completed by Nokel81** 2021-08-23 14:36 UTC
Labels: bug, area/extension
