### ISSUE TITLE
Cannot read property 'showTimestamps' of undefined

### ISSUE THREAD

**Issue by mgagliardo91** [lensapp/lens#2547] opened 2021-04-16 15:05 UTC
**Describe the bug**

Running into a stack trace error frequently. See logs below for output.

**Environment (please complete the following information):**

```
Lens: 4.2.1
Electron: 9.4.0
Chrome: 83.0.4103.122
Node: 12.14.1
© 2021, Mirantis, Inc.
```
- OS: OSX

**Logs:**
```
Component stack:


    at RF (http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:8289141)
    at div
    at div
    at xF (http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:8295312)
    at footer
    at div
    at IU (http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:8500156)
    at AA (http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:7677082)
    at t (http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:222042)
    at kU (http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:8501660)
```

```
Error stack:

 
TypeError: Cannot read property 'showTimestamps' of undefined
    at RF.renderResourceSelector (http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:8289963)
    at RF.render (http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:8290478)
    at Ce (http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:13973)
    at http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:7533054
    at ce (http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:12079)
    at e.track (http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:23443)
    at RF.s [as render] (http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:7533002)
    at RF.Ee (http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:7533150)
    at RF.t.render (http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:7532106)
    at _s (http://77d78142-e716-4686-b631-53abe35b9f41.localhost:53453/build/Lens.js:2:4631182)
```

**Comment by jim-docker** [comment] 2021-04-19 12:39
duplicate of #2458

**Closed as completed** 2021-04-19 12:40 UTC
Labels: bug
