### ISSUE TITLE
Broken link on the Windows App

### ISSUE THREAD

**Issue by hrittikhere** [lensapp/lens#2900] opened 2021-05-28 13:19 UTC
**Describe the bug**
The hyperlink 'here' is pointing to https://docs.k8slens.dev/v4.2.4/latest/clusters/adding-clusters/ that happens to be broken on the windows app.
![image](https://user-images.githubusercontent.com/67012359/119989571-f5aaeb00-bfe4-11eb-8bb9-aa0535231ed2.png)

**To Reproduce**
1. Go to 'Add clusters'
2. Click on 'here'
3. See error on your browser

**Expected behavior**
A link with the documentation must open up.

**Screenshots**
![image](https://user-images.githubusercontent.com/67012359/119989850-47537580-bfe5-11eb-8dab-fd30f75c4af8.png)

**Environment (please complete the following information):**
- Lens Version: 4.2.4
- OS: Windows 10 Pro 20H2
- Installation method (e.g. snap or AppImage in Linux): .exe on windows

**Additional context**
N/A

**Comment by jim-docker** [comment] 2021-05-31 13:11
Duplicate of #2769

**Closed as completed by jim-docker** 2021-05-31 13:11 UTC
Labels: bug
