### ISSUE TITLE
Remember the filter/search string

### ISSUE THREAD

**Issue by zerowebcorp** [lensapp/lens#3510] opened 2021-07-23 18:53 UTC
**What would you like to be added**:
A feature to remember the search string in all the filters such as "Search Pods", "Search Deployments" etc. 

**Why is this needed**:
A lot of times, when we are troubleshooting the applications, we have to look for the Deployments and Pods. When dealing with hundreds of deployments, we always have to filter the deployment by searching with the name of the deployment. We also have to goto Pods page to understand how many pods are unhealthy and possibly ssh into a pod. Every time when I navigate away from the Deployment or Pods page, the search/filter string is reset. If it is remembered, then it would help with the filtering

**Environment you are Lens application on:**
K8s
- Kubernetes distribution: AKS
- Desktop OS: Windows10

**Comment by MarcMielke** [comment] 2021-11-08 14:34
Is this on the plate for the next release? Would be really helpful.

**Comment by Nokel81** [comment] 2022-02-14 15:27
Closing as duplicate of #271

**Closed as completed by Nokel81** 2022-02-14 15:27 UTC
Labels: enhancement, area/search
