### ISSUE TITLE
High CPU usage in background, many lens.exe processes

### ISSUE THREAD

**Issue by spyro2000** [lensapp/lens#1733] opened 2020-12-10 09:54 UTC
Sometimes, lens uses more than one (may be part of the design). Each of the processes uses about 10% CPU on my machine which leads to significant load while doing absolutely nothing (just minimized in the background).

After clicking on 4 cluster configs it already looks like this:

![image](https://user-images.githubusercontent.com/8479925/101756030-e0dda800-3ad5-11eb-85b4-550501a1d522.png)

**To Reproduce**
1. Import some cluster configs
2. Click on the tab icons
3. Open process explorer

**Expected behavior**

CPU-load should be trivial when not used.

**Screenshots**

![image](https://user-images.githubusercontent.com/8479925/101755695-788ec680-3ad5-11eb-80c7-ffe2c17113d6.png)

**Environment (please complete the following information):**
- Lens Version: 4.0.0
- OS: Win7x64
- Installation method (e.g. snap or AppImage in Linux): Installer

**Comment by spyro2000** [comment] 2020-12-11 08:26
Update: Many of the processes are still active after lens was closed and have to be al killed one-by-one in the task manager:

![image](https://user-images.githubusercontent.com/8479925/101880258-e2b97100-3b92-11eb-9fad-e2f0e3e95e8b.png)

**Comment by nevalla** [comment] 2020-12-14 12:34
I think we need to verify that all processes are closed properly when exiting Lens application. Could not reproduce this on MacOS so probably Windows version need more actions regarding this.

Multiple Lens processes issue is fixed by #1742.

**Comment by jakolehm** [comment] 2020-12-17 18:00
I think this issue was fixed in #1742. Let's reopen if problem persists.

**Closed as completed by jakolehm** 2020-12-17 18:00 UTC
Labels: bug, area/windows

**Comment by borgez** [comment] 2021-02-11 03:09
@jakolehm the problem is not in the number of processes, but in the constant load of each of them
