### ISSUE TITLE
Search queries

### ISSUE THREAD

**Issue by biqas** [lensapp/lens#2338] opened 2021-03-15 18:05 UTC
**What would you like to be added**:
Search query history and if switching between screens the possibility to preserve the search query.

**Why is this needed**:
Switching between screens during analysis need to preserve the state which was left.

**Environment you are Lens application on:**

- Kubernetes distribution: [AKS, Minikube]
- Desktop OS: Windows 10

**Comment by vshakirova** [comment] 2021-03-16 05:10
jfi: similar request https://github.com/lensapp/lens/issues/271

**Comment by Nokel81** [comment] 2021-03-25 19:31
duplicate of #271

**Closed as completed by Nokel81** 2021-03-25 19:31 UTC
Labels: enhancement
