### ISSUE TITLE
Stop Inserting Lens as a Login Item (MacOS)

### ISSUE THREAD

**Issue by StephenMP** [lensapp/lens#2420] opened 2021-03-31 14:08 UTC
**What would you like to be added**:
When you install Lens and every time it updates on Mac, it gets inserted as a Login Item for the current user which makes it startup on user login. This is quite annoying as I only want to start Lens when I want to use it, please remove this functionality.

**Why is this needed**:
Explained above, but in a nutshell, it doesn't make sense for Lens to always insert itself as a Login Item

**Comment by Moskovych** [comment] 2021-04-02 10:16
@StephenMP , looks like you faced with the same issue, look: https://github.com/lensapp/lens/issues/2107
After few updates I deleted lens and installed with `brew`. Now look like it fixed (of course with unchecked  button).

**Comment by jim-docker** [comment] 2021-04-06 13:21
duplicate of #2107

**Closed as completed by jim-docker** 2021-04-06 13:21 UTC
Labels: enhancement
