### ISSUE TITLE
App didn't start with non-empty `lens-cluster-store.json`

### ISSUE THREAD

**Issue by aleksfront** [lensapp/lens#3242] opened 2021-07-01 11:03 UTC
Lens failed to start if:
1. It doesn't have `lens-hotbar-store.json`
2. It has `lens-cluster-store.json` with some data in it.

Log error:
```
info: 📟 Setting Lens as protocol client for lens://
info: 📟 Protocol client register succeeded ✅
info: 🚀 Starting Lens from "/Users/alexfront/Library/Application Support/Lens"
info: 🐚 Syncing shell environment
info: 💾 Loading stores
info: [STORE]: LOADED from /Users/alexfront/Library/Application Support/Lens/lens-user-store.json
[ { filePath: '/Users/alexfront/.kube' } ]
info: [STORE]: LOADED from /Users/alexfront/Library/Application Support/Lens/lens-cluster-store.json
Creating new hotbar for default
Creating new hotbar for mynewworkspace
Creating new hotbar for workspace1
Adding cluster 48137dc63b625136cbb9ff361c5256a3 to Workspace: mynewworkspace
Adding cluster ae0832a2f0cc8d91836a7c8fa915f146 to default
Adding cluster 7af556eeb5d9dab2aeb5ccf10acfe7ec to default
Adding cluster 2dbd120bc67f1b440f90c94f7c2224cf to default
(node:48044) UnhandledPromiseRejectionWarning: Error: Something went wrong during the migration! Changes applied to the store until this failed migration will be restored. TypeError: Cannot read property 'name' of undefined
    at Conf._migrate (/Users/alexfront/Projects/lens/dist/mac/Lens.app/Contents/Resources/app.asar/node_modules/conf/dist/source/index.js:407:23)
    at new Conf (/Users/alexfront/Projects/lens/dist/mac/Lens.app/Contents/Resources/app.asar/node_modules/conf/dist/source/index.js:144:18)
    at Yi.load (/Users/alexfront/Projects/lens/dist/mac/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:15856)
    at new Yi (/Users/alexfront/Projects/lens/dist/mac/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:155955)
    at Function.createInstance (/Users/alexfront/Projects/lens/dist/mac/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:34367)
    at n (/Users/alexfront/Projects/lens/dist/mac/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:244329)
    at next (<anonymous>)
    at i (/Users/alexfront/Projects/lens/dist/mac/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:246410)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:48044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:48044) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Steps to reproduce:
1. Start Lens 5.
2. Close Lens.
3. Remove `lens-hotbar-store.json`.
4. Start Lens again.

**Comment by aleksfront** [comment] 2021-07-01 11:20
After further testing is seems that error happens only in #3227 branch.

**Comment by Nokel81** [comment] 2021-07-06 13:24
Will close this as it only happens on the #3227 branch and will be fixed there (namely, is not a bug on master)

**Closed as completed by Nokel81** 2021-07-06 13:24 UTC
Labels: bug, migrations
