### ISSUE TITLE
Cannot install extensions

### ISSUE THREAD

**Issue by varunyn** [lensapp/lens#2662] opened 2021-04-28 18:09 UTC
**Describe the bug**
When trying to install extensions,  it is failing. Tried to download extension and gave file path also tried via URL.

This is what error msg looks like,
`Installing extension @nevalla/kube-resource-map@0.2.0 has failed: ENOENT: no such file or directory, stat '/var/folders/m9/k655rqcd5cx0tc2fr78n8gzm0000gn/T/lens-extensions/nevalla-kube-resource-map-0.2.0.tgz'`

**Expected behavior**
- Extension should install successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/26843227/116451786-8d6cbc00-a822-11eb-9f9f-f140a17e4a86.png)

**Environment (please complete the following information):**
- Lens Version: 4.2.3
- OS: macOS 10.15.7
- Installation method (e.g. snap or AppImage in Linux): dmg file from site

**Logs:**
Logs from console when trying to install extension
```
info: Install from D&D
console.js:124 info: Unpacking extension @nevalla/kube-resource-map@0.2.0 {"fileName":"nevalla-kube-resource-map-0.2.0.tgz","tempFile":"/var/folders/m9/k655rqcd5cx0tc2fr78n8gzm0000gn/T/lens-extensions/nevalla-kube-resource-map-0.2.0.tgz"}
console.js:124 info: [EXTENSION-INSTALLATION]: installing nevalla-kube-resource-map-0.2.0.tgz has failed: ENOENT: no such file or directory, stat '/var/folders/m9/k655rqcd5cx0tc2fr78n8gzm0000gn/T/lens-extensions/nevalla-kube-resource-map-0.2.0.tgz' {"error":{"errno":-2,"code":"ENOENT","syscall":"stat","path":"/var/folders/m9/k655rqcd5cx0tc2fr78n8gzm0000gn/T/lens-extensions/nevalla-kube-resource-map-0.2.0.tgz"}}
```

**Comment by jim-docker** [comment] 2021-05-03 12:56
duplicate of #2688

**Closed as completed by jim-docker** 2021-05-03 12:56 UTC
Labels: bug
