### ISSUE TITLE
Item view popup not working on k8s 1.20

### ISSUE THREAD

**Issue by zycon** [lensapp/lens#1730] opened 2020-12-10 07:32 UTC
Item view popup not showing in k8s 1.20,  its working fine with 1.18

![image](https://user-images.githubusercontent.com/36449874/101735184-eb4e7080-3ada-11eb-851b-e5f4bfb87449.png)

Nothing Popups when i click 1.20 in Lens, 

**To Reproduce**
1. Click any item, it should show config/view in a sidebar/popup, but nothing happens in 1.20

**Expected behavior**
![image](https://user-images.githubusercontent.com/36449874/101735374-3cf6fb00-3adb-11eb-985e-71bdae08f0d4.png)
Should able to see the popup with data

**Environment (please complete the following information):**
- Lens Version:
- OS: Macos 10.15.6 (19G73
- brew , tried on 3.5 and 4.0

**Additional context**
Tried on fresh cluster setups

**Comment by Nascire** [comment] 2020-12-10 13:07
Can confirm for Windows, Lens 4.0.1

**Comment by nevalla** [comment] 2020-12-14 12:36
Duplicate of #1711. Let's monitor the issue resolution there.

**Closed as completed by nevalla** 2020-12-14 12:36 UTC
Labels: bug
