### ISSUE TITLE
Lens blocks the Internet on my device

### ISSUE THREAD

**Issue by alex-kovalchuk** [lensapp/lens#8013] opened 2024-02-05 10:38 UTC
**Describe the bug**
After a certain amount of time Lens has been running, the Internet is blocked. This problem appears quite rarely and usually after intensive interaction with several K8S instances.

When this problem occurs, I cannot connect to any resource through the browser, all messengers stop working, reconnecting to other Wifi access points does not solve the problem. Sometimes I even forget that I need to turn off Lens for this problem to go away.

I can’t say which version of Lens this problem started with, but I’ve had it for at least 1 year, but I was hoping it would be fixed without my issue.

**To Reproduce**
1. Open Lens
2. Working with multiple k8s instances
3. Waiting for a problem with network

**Environment:**
- Lens Version: 2024.1.300751-latest
- OS: MacOS Ventura 13.6.2

**Additional context**
It seems to me that this problem is caused by the Lens proxy process. It freezes frequently.

**Comment by msa0311** [comment] 2024-02-06 10:38
Thanks for reporting this, we have just responded to a duplicate of this issue here: https://github.com/lensapp/lens/issues/6063#issuecomment-1929229531

**Closed as completed by msa0311** 2024-02-06 10:38 UTC
Labels: bug
