### ISSUE TITLE
nodes中的disk信息只获取了"/", 例如挂载的/data数据卷无法显示容量

### ISSUE THREAD

**Issue by mengdehuihuang** [lensapp/lens#3446] opened 2021-07-20 02:57 UTC
![image](https://user-images.githubusercontent.com/48198919/126255056-3bb4ac83-59ef-49da-b5f5-c5e50fc7c058.png)
![image](https://user-images.githubusercontent.com/48198919/126255079-b71d1571-c8f3-4e1c-9922-b0180a451606.png)

**Comment by Nokel81** [comment] 2022-08-04 20:24
Given that you it is reporting that you are using 3% of the data and it looks like the graphs are about 3% full I am closing as "working as intended"

**Closed as not planned by Nokel81** 2022-08-04 20:24 UTC
Labels: enhancement
