### ISSUE TITLE
[v4.0.1] HPA properties page does not display any information

### ISSUE THREAD

**Issue by quantm241** [lensapp/lens#1743] opened 2020-12-11 04:56 UTC
**Describe the bug**
HPA properties page does not display any information.

**To Reproduce**
1. Go to 'Configuration' > 'HPA'
2. Click on any HPA

**Expected behavior**
HPA properties will be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/34535573/101865010-7d787680-3bb8-11eb-8a52-82bcf033dc88.png)

**Environment (please complete the following information):**
- Lens Version: 4.0.1
- OS: RHEL 8
- Installation method (e.g. snap or AppImage in Linux): snap

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by jakolehm** [comment] 2020-12-11 05:46
Duplicate of #1723.

**Closed as completed by jakolehm** 2020-12-11 05:46 UTC
Labels: bug
