### ISSUE TITLE
Can't see HPA Configurations

### ISSUE THREAD

**Issue by mambax** [lensapp/lens#1769] opened 2020-12-14 09:39 UTC
**Describe the bug**
I can not see HPA in Configuration.

**To Reproduce**
If I'd know them I would not report 🤣

**Expected behavior**
See this
![image](https://user-images.githubusercontent.com/5472171/102064262-607db680-3df7-11eb-9d28-e975cb672594.png)

**Screenshots**
I see
![image](https://user-images.githubusercontent.com/5472171/102064285-683d5b00-3df7-11eb-84a3-25ffd797621c.png)

**Environment (please complete the following information):**
- Lens Version: 4.0.2
- OS: OSX 11.0.1
- Installation method (e.g. snap or AppImage in Linux): Download from Website

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
❯ /Applications/Lens.app/Contents/MacOS/Lens
info: 🚀 Starting Lens from "/Users/xxxx/Library/Application Support/Lens"
info: Checking for update
info: [STORE]: LOADED from /Users/xxxx/Library/Application Support/Lens/config.json
info: [STORE]: LOADED from /Users/xxxx/Library/Application Support/Lens/lens-cluster-store.json
info: [STORE]: LOADED from /Users/xxxx/Library/Application Support/Lens/lens-workspace-store.json
info: [STORE]: LOADED from /Users/xxxx/Library/Application Support/Lens/lens-extensions.json
info: [STORE]: LOADED from /Users/xxxx/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx-dt","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx-au","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: LensProxy server has started at http://localhost:60365
info: [EXTENSION-DISCOVERY] watching extension add/remove in /Users/xxxx/.k8slens/extensions
info: [EXTENSION-DISCOVERY] loading extensions from /Users/xxxx/Library/Application Support/Lens
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx-au","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: "xxxx/medo-dt" init success {"id":"xxxx","context":"xxxx.io/medo-dt","apiUrl":"xxxxxxxxxxxx"}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx-au","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: "sb-1.coreinfra.io/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: "xxxx/medo-au" init success {"id":"xxxx","context":"xxxx/medo-au","apiUrl":"xxxx"}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER-MANAGER]: init cluster {"id":"xxxx","name":"xxxx","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo-au" init success {"id":"xxxx","context":"xxxx/medo-au","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo-au" init success {"id":"xxxx","context":"xxxx/medo-au","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [CLUSTER]: "xxxx/medo" init success {"id":"xxxx","context":"xxxx/medo","apiUrl":"xxxx"}
info: [EXTENSION-INSTALLER] installing dependencies at /Users/xxxx/Library/Application Support/Lens
info: Update for version 4.0.2 is not available (latest version: 4.0.2, downgrade is disallowed).
info: [EXTENSION]: enabled lens-license@0.1.0
telemetry main extension activated
info: [STORE]: LOADED from /Users/xxxxx/Library/Application Support/Lens/extension-store/lens-telemetry/preferences-store.json
info: [EXTENSION]: enabled lens-telemetry@0.1.0
info: [CLUSTER]: activate {"id":"xxxx","name":"xxxx/medo","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: bind events {"id":"xxxx","name":"xxxx/medo","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: reconnect {"id":"xxxx","name":"xxxx/medo","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
info: [KUBE-AUTH]: out-channel "kube-auth:xxxx" {"data":"Authentication proxy started\n","meta":{"id":"xxxx","name":"xxxx/medo","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}}
(node:49824) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: <file>
  name: 
contexts:
- context:
    cluster: 
    user:
  name: 
current-context: ""
kind: Config
preferences: {}
users:
- name:
  user:
    auth-provider:
      config:
        client-id: loginapp
        client-secret:
        id-token: 
        idp-issuer-url: 
        refresh-token: 
      name: oidc

```

**Additional context**
My rights acc. to infra are set as:
```
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  - horizontalpodautoscalers/status
  verbs:
  - get
  - list
  - watch
```

I also ran Lens with `DEBUG=true`, there is no log output about HPA.

**Comment by giannisioannou-tomtom** [comment] 2020-12-14 11:46
Duplicate of #1743
Will be fixed in #1745

**Closed as completed** 2020-12-14 12:28 UTC
Labels: bug

**Comment by mambax** [comment] 2020-12-14 12:37
@giannisioannou-tomtom Why does it work for my colleague though? 🧐

**Comment by nevalla** [comment] 2020-12-14 12:39
> @giannisioannou-tomtom Why does it work for my colleague though? 🧐

Is he/she having already Lens 4.0.2? This should be included in that release.

**Comment by mambax** [comment] 2020-12-14 13:20
No but I have 4.0.2 and cant see it 😨 
![image](https://user-images.githubusercontent.com/5472171/102085843-78fdc900-3e17-11eb-95c8-8bff2b5614b2.png)
![image](https://user-images.githubusercontent.com/5472171/102085873-80bd6d80-3e17-11eb-9386-b011c2bf109b.png)

I fear we have a privilege problem but we cant debug it because there is no error or similar what privilege is missing 😢

**Comment by giannisioannou-tomtom** [comment] 2020-12-14 20:21
> @giannisioannou-tomtom Why does it work for my colleague though?

Hello, I just copy/pasted the same reply I got for exactly the same bug I reported a couple of days ago. I did download version 4.0.2 today and the HPA details panel appears as it used to but I'm afraid I don't know why it works for your colleague, I'm not involved in the development of Lens, I'm just a very impressed user.

**Comment by mambax** [comment] 2020-12-15 07:56
I understand 😊
@nevalla I fear this was closed a bit prematurely. I run 4.0.2 and can't see HPA. I am totally aware that it could be a permission issue yet it's not clear to us how to debug it 😢

**Comment by zagr0** [comment] 2021-11-17 10:59
the same issue still exist and for the newer versions 5.2.5, the HPA is missing in Configuration menu
horizontalpodautoscalers can be listed with kubectl
