### ISSUE TITLE
Extension appears to be enabled but can't be found

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#1684] opened 2020-12-07 23:47 UTC
When installing an extension from tarball through the UI it appears to install successfully, and can be enabled but does not actually get loaded.

Root cause is actually the symlink points to a non-existent folder.

From the logs:
```
info: [EXTENSION-DISCOVERY] Added extension @mirantis/lens-extension-cc
info: [STORE]: SAVING /Users/jimehrismann/Library/Application Support/Lens/lens-extensions.json
[EXTENSIONS-LOADER]: can't load extension main at /Users/jimehrismann/Library/Application Support/Lens/node_modules/@mirantis/lens-extension-cc/dist/main.js: Error: Cannot find module '/Users/jimehrismann/Library/Application Support/Lens/node_modules/@mirantis/lens-extension-cc/dist/main.js'
```

`~/Library/Application Support/Lens/node_modules/@mirantis/lens-extension-cc` is a symlink pointing to `~/.k8slens/extensions/lens-extension-cc` but the extension is actually installed in `~/.k8slens/extensions/mirantis--lens-extension-cc`

Apart from this, it seems odd that the link is created in `~/Library/Application Support/Lens/node_modules/` and points to the files installed in `~/.k8slens/extensions/`. Shouldn't it be the other way around? The extension should actually be installed under `~/Library/Application Support/Lens/node_modules/` and a link to it be created in `~/.k8slens/extensions/`?

affects 4.0.0

**Comment by panuhorsmalahti** [comment] 2020-12-08 08:08
Can't reproduce just yet. In any case it's correct that the symlink is from `~/Library/Application Support/Lens/node_modules/` to `~/.k8slens/extensions/`.

**Comment by panuhorsmalahti** [comment] 2020-12-08 08:28
Reproduces on production build, not dev.

**Comment by panuhorsmalahti** [comment] 2020-12-08 09:20
This is what probably happened:
1. User copied extension to `/Users/<username>/.k8slens/extensions/lens-extension-cc`
2. User uninstalled extension from the UI (or just deleting the folder manually).
3. User installed extension from the Lens UI.

At this point `/Users/<username>/Library/Application Support/Lens/node_modules/@mirantis/lens-extension-cc` still points to the old `/Users/<username>/.k8slens/extensions/lens-extension-cc`.

I think the fix would be actually run npm uninstall (or something) to remove it from node_modules. It's already removed from package.json and `/Users/<username>/.k8slens/extensions`

**Comment by panuhorsmalahti** [comment] 2020-12-08 11:28
Users encountering this bug can for now remove the broken symlink manually from e.g. `/Users/<username>/Library/Application Support/Lens/node_modules/@publisher/extension`.

**Comment by stefcameron** [comment] 2020-12-08 15:46
> This is what probably happened:
> 
> 1. User copied extension to `/Users/<username>/.k8slens/extensions/lens-extension-cc`
> 2. User uninstalled extension from the UI (or just deleting the folder manually).
> 3. User installed extension from the Lens UI.

Yep, that's what happened... 😄  (I just deleted the folder manually, which was a symlink in my case, because that's also how I had installed the extension in the first place...)

**Comment by panuhorsmalahti** [comment] 2020-12-11 08:09
Should be fixed (well enough) now.

We could still handle the following case: user removes the extension manually and then starts Lens. Even in this case the broken symlink should be fixed on the next install.

**Closed as completed by panuhorsmalahti** 2020-12-11 08:09 UTC
Labels: bug, area/extension
