### ISSUE TITLE
Javascript errors on exit (Desktop)

### ISSUE THREAD

**Issue by paalandreassen** [lensapp/lens#414] opened 2020-06-09 07:27 UTC
**Describe the bug**
Everytime I exit the Lens desktop application (3.4.0) I get a javascript error:
> Cannot set headers after they are sent to client

**To Reproduce**
1. Open Lense
2. Connect to a cluster
3. Exit

**Expected behavior**
Not display an error

**Screenshots**
[Error message](https://imgur.com/a/2S2urdM)

**Environment (please complete the following information):**
- Lens Version: 3.4.0
- OS: Windows 10, x64
- Installation method (e.g. snap or AppImage in Linux):  Setup exe

**Comment by nevalla** [comment] 2020-06-09 08:00
Duplicate of #377

**Closed as completed by nevalla** 2020-06-09 08:00 UTC
Labels: duplicate
