### ISSUE TITLE
Error while adding cluster(s): User Exec command "aws" not found on host. Please ensure binary is found in PATH or use absolute path to binary in Kubeconfig

### ISSUE THREAD

**Issue by sanjaykulkarni04** [lensapp/lens#2914] opened 2021-05-31 10:25 UTC
Hi,

I am getting "**Error while adding cluster(s): User Exec command "aws" not found on host. Please ensure binary is found in PATH or use absolute path to binary in Kubeconfig**" while adding cluster in **Lens: 4.2.4**.

Can you please advise? PFA screenshots.

Thanks,
Sanjay

![image](https://user-images.githubusercontent.com/36174701/120179778-9c32fe00-c228-11eb-8041-6fd0b2077093.png)

![image](https://user-images.githubusercontent.com/36174701/120179806-a654fc80-c228-11eb-884c-95ded6d13381.png)

![image](https://user-images.githubusercontent.com/36174701/120179820-abb24700-c228-11eb-8759-ebaafe3cdaed.png)

**Comment by jim-docker** [comment] 2021-05-31 13:37
Duplicate of #2290

**Closed as completed by jim-docker** 2021-05-31 13:37 UTC
Labels: bug
