### ISSUE TITLE
4.2.0 does not support kubernetes version v1.7.8

### ISSUE THREAD

**Issue by goudai** [lensapp/lens#2504] opened 2021-04-12 02:12 UTC
# 4.2.0 does not support kubernetes version v1.7.8
```js
Component stack:
    at Sidebar (http://cd111aa3-67c1-4b32-bf0b-b54bd861d5a6.localhost:59376/build/Lens.js:2:8495037)
    at aside
    at div
    at IU (http://cd111aa3-67c1-4b32-bf0b-b54bd861d5a6.localhost:59376/build/Lens.js:2:8500156)
    at AA (http://cd111aa3-67c1-4b32-bf0b-b54bd861d5a6.localhost:59376/build/Lens.js:2:7677082)
    at t (http://cd111aa3-67c1-4b32-bf0b-b54bd861d5a6.localhost:59376/build/Lens.js:2:222042)
    at kU (http://cd111aa3-67c1-4b32-bf0b-b54bd861d5a6.localhost:59376/build/Lens.js:2:8501660)
```
```js
Error stack:

 
TypeError: Cannot read property '0' of undefined
    at yf.getVersion (http://cd111aa3-67c1-4b32-bf0b-b54bd861d5a6.localhost:59376/build/Lens.js:2:7872512)
    at yf.getResourceApiBase (http://cd111aa3-67c1-4b32-bf0b-b54bd861d5a6.localhost:59376/build/Lens.js:2:7872161)
    at http://cd111aa3-67c1-4b32-bf0b-b54bd861d5a6.localhost:59376/build/Lens.js:2:8495380
    at Array.map (<anonymous>)
    at http://cd111aa3-67c1-4b32-bf0b-b54bd861d5a6.localhost:59376/build/Lens.js:2:8495345
    at Array.map (<anonymous>)
    at BU.get crdSubMenus (http://cd111aa3-67c1-4b32-bf0b-b54bd861d5a6.localhost:59376/build/Lens.js:2:8495227)
    at ce (http://cd111aa3-67c1-4b32-bf0b-b54bd861d5a6.localhost:59376/build/Lens.js:2:12079)
    at e.computeValue (http://cd111aa3-67c1-4b32-bf0b-b54bd861d5a6.localhost:59376/build/Lens.js:2:18380)
    at e.trackAndCompute (http://cd111aa3-67c1-4b32-bf0b-b54bd861d5a6.localhost:59376/build/Lens.js:2:18206)
```

**Comment by jim-docker** [comment] 2021-04-12 13:21
duplicate of #2438

**Closed as completed by jim-docker** 2021-04-12 13:21 UTC
Labels: bug
