### ISSUE TITLE
Lens automatically updates on reopen

### ISSUE THREAD

**Issue by hansiemithun** [lensapp/lens#2216] opened 2021-02-24 09:22 UTC
This is not working anymore, the Lens is automatically updated on reopen. 

Sometime back, this was fixed from: https://github.com/lensapp/lens/pull/1941. We also observed a notification popup requesting for update with yes or no option in mac. But later we are not seeing such notifications.

It will be good to provide an option also for stop updates too. And always take confirmation from the users.

**Environment:** mac

_Originally posted by @hansiemithun in https://github.com/lensapp/lens/pull/1941#issuecomment-784931915_

**Comment by Moskovych** [comment] 2021-03-01 11:11
+1.
The same on MacOS with version `4.1.0`, always ask to update to `4.1.3`.

**Comment by jim-docker** [comment] 2021-03-01 14:06
Can you wait to see if this is fixed in the next patch release, or minor release as we are still addressing some update issues?

**Comment by Nokel81** [comment] 2021-03-08 16:32
Is this still a problem?

**Comment by hansiemithun** [comment] 2021-03-10 07:40
At present, i have manually updated to 4.1.4 now, cant comment or assure if this is fixed. But we can close this ticket now...

**Comment by Nuru** [comment] 2021-04-30 19:41
@Nokel81 @jim-docker  This is still a problem. I was automatically updated from 4.2.1 to 4.2.2 and today from 4.2.2 to 4.2.3, despite clicking "No" in the update notification.

Please reopen this issue.

**Comment by Nokel81** [comment] 2021-05-01 15:27
Reproduced

**Comment by ZheyangSong** [comment] 2021-09-20 23:46
@Nokel81 any idea when this will be fixed? The frequent unexpected breakage caused by auto-update is annoying and distracting.

**Comment by Nokel81** [comment] 2021-09-21 14:06
@ZheyangSong what version are you using? This has most certainly been fixed in 5.X

**Comment by Nokel81** [comment] 2021-11-03 20:07
Closing as we no longer support 4.X and this has been fixed in 5.X

**Closed as completed by Nokel81** 2021-11-03 20:07 UTC
Labels: bug, area/auto-update

**Comment by dcole-gsn** [comment] 2023-01-19 10:41
Hi,
This occurred to me going from 6.25 -> 6.3.
OpenLens automatically updated itself. Can this please get fixed? As 6.3 is doesn't work for us, it connects but doesn't show any information about the connected cluster.
Kind regards.
