### ISSUE TITLE
Cannot see any resource which is CDR ie ISTIO VirtualService

### ISSUE THREAD

**Issue by McMlok** [lensapp/lens#786] opened 2020-09-01 17:33 UTC
**Describe the bug**
I have in my cluster some CDR like ISTIO, WSO2.... I see them in left menu Custom Resources under I see every CDR I have instaled on my cluster but when I click on any service like ISTIO Virtual Service I don't see any items. But when I run kubectl get VirtualService -n wso2 I see one. See screenshot

**To Reproduce**
1. Install ISTIO to your cluster
2. Define any VirtualService
3. Open Lens
4. Go to Custom Resources -> netowrking.istio.... -> VirtualService
5. Item list is empty

**Expected behavior**
List contains one item

**Screenshots**
[ScreenShot](https://gist.githubusercontent.com/McMlok/1a544d957bb55ce39b7ddd230d2b7eda/raw/3b36e61dd017fed912e26487931c85d463b856dd/Lens-CDR-error.png)

**Environment (please complete the following information):**
- Lens Version: 3.6.0-beta2
- OS: Windows 10 1809
- Installation method (e.g. snap or AppImage in Linux): Windows exe file

**Comment by ocdi** [comment] 2020-09-01 21:39
I'm pretty sure this is a dupe of #726

**Comment by McMlok** [comment] 2020-09-02 18:53
I don't know if it helps, but I open Developer Tools and look to network request and found this.

`http://152947be-7bd3-44ee-864e-df1d065fb607.localhost:47009/api-kube/apis/networking.istio.io/undefined/virtualservices?`

It end with HTTP 404

**Comment by ocdi** [comment] 2020-09-02 20:14
Yep definitely the same issue. The pr linked to that issue solved it for me. Out of interest what is the kubernetes  cluster version?

**Comment by McMlok** [comment] 2020-09-03 06:57
I have K8s 1.16.5 in docker for desktop (2.3.0.4).

**Comment by nevalla** [comment] 2020-09-04 10:29
Fixed in https://github.com/lensapp/lens/pull/718.

**Closed as completed by nevalla** 2020-09-04 10:29 UTC
